### ISSUE TITLE
doesn't start

### ISSUE THREAD

**Issue by adaptabi** [da2x/EdgeDeflector#1]
doesn't start at all on latest w10

**Comment by da2x** [comment]
Did you read the installation instructions? You just double click it once and that is it. The program doesn't really do anything, show anything, nor does it keep running in the background. You'll not even see it when you click on a link in Cortana, it will just run for a microsecond to redirect the link to your default browser. I'll add a confirmation message when you run it the first time to clarify.

**Comment by adaptabi** [comment]
Yes, but when I type on `cortana` and press enter the search still opens in Edge.
There is not even displayed `EdgeDeflector` on default apps
![image](https://cloud.githubusercontent.com/assets/485535/22993737/64914588-f3c4-11e6-985d-4e704540d22e.png)

**Comment by da2x** [comment]
Could you please restart your PC and let me know if that resolvedthethe problem? If it does, I think I know what the problem is.

**Comment by adaptabi** [comment]
Negative. Same result.
Note Chrome was already default browser but that din't help either.
![image](https://cloud.githubusercontent.com/assets/485535/22994209/65c2e40a-f3c6-11e6-9a23-21a2b769181a.png)

Still just Edge on the `URL:microsoft-edge` default

**Comment by adaptabi** [comment]
It worked! It seems I have moved the `exe` after being run to a `proper directory`!!

**Comment by da2x** [comment]
I’ll still work on a info dialog to improve usability. Thank you for your interest and feedback!

**Comment by adaptabi** [comment]
sounds good, thank you!

**Comment by skysco** [comment]
I am having issues with edge deflector staring up... 
I am attempting to use Cortana to search through Google(Chrometenna) chrome, via google search
I have had this set up running once before, although something has caused it to not work... 
Upon reinstalling edge deflector; I am no longer able to view web results when searching through cortenna at all. I click on see web results; and the cortana menu disappears...yet nothing loads.... its as if something isnt making it to the end point or is interfering with the load of my web results... 

Thank you for your assistance in making this any clearer, any help is greatly appreciated.

**Comment by maltonge** [comment]
Yes same issue as Skysco above,  On my new updated machine this no longer works,  installed edgedeflector many times and openly refer to others.  It seems windows have patched this in their latest update.  A real shame,  I hate Microsoft forcing their crap on me,  another thing is the font size can not be changed anywhere in the latest windows 10.  I can not see anything,  hurting my back leaning over to read.  I think ill give ubuntu another try,  its been 5 years since using I think they would have ironed out their creases by now.

**Comment by da2x** [comment]
@maltonge, have you downloaded the [latest release](https://github.com/da2x/EdgeDeflector/releases/latest)?

I personally recommend [Fedora Linux](https://getfedora.org/en/workstation/). You don’t have to deal with this bullshit, and if worst comes to worst – you can just change things to work the way you want yourself.

**Comment by maltonge** [comment]
Hey big thanks, The link you provided works great, just checking my browser
history I can confirm the version I installed previously was 1.0.1.0  which
did not work.  I did not see any other versions last night, strange.
Anyway big thanks the update to 1.1.3.0 works perfectly.  Updates now
turned off and this should work now for the life of the laptop.  Thanks
again @da2x
