### ISSUE TITLE
Search system redirections

### ISSUE THREAD

**Issue by volsend** [da2x/EdgeDeflector#10]
Hi! 

I very like your program since it allows me to make search through my startmenu. But, I don't feel well with bing, so I need to install 3-rd party extensions to my browser to redirect all the requests to google instead of bing. 

So, this would be nice if there was a possibility to configure the re-directions between search system. For example, in the nearby file lying in the application folder.

**Comment by da2x** [comment]
Please see [issue #4](https://github.com/da2x/EdgeDeflector/issues/4#issuecomment-283579074).
