### ISSUE TITLE
Still Opening in MS Edge

### ISSUE THREAD

**Issue by LRNGCODE** [da2x/EdgeDeflector#100]
Despite following these [troubleshooting tips](https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting), all of my search results from the "type here to search" bar opens in MS Edge browser.

**Comment by Fordi** [comment]
+1

**Comment by gaylesbean** [comment]
Same here. I've been using this for months and it was working fine before, but I just had to factory reset my computer and now that I've redownloaded EdgeDeflector it's no longer working, even after following all of the troubleshooting steps.

**Comment by da2x** [comment]
Please confirm that EdgeDefelctor is set as the default app in the [third troubleshooting step](https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting).

**Comment by RadegasTCZ** [comment]
Tried the Win + R -> microsoft-edge://example.com/ and it prompted me with dialog for default program.

**Comment by Hexatonix72** [comment]
After installing go to Settings>Default apps>Choose default apps by protocol. Then, scroll down to where it says: "MICROSOFT-EDGE URL:microsoft-edge", and select EdgeDeflector as the default app.
