### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by opentitan** [da2x/EdgeDeflector#101]
Couldn't find other way to simply say "Thank you" to the authors on GitHub

**Comment by da2x** [comment]
You're welcome. I'm happy to help enforce the user's right to have their computers default to their preferred programs.

GitHub's "thank you" options are in the top right corner: the Star and Sponsor buttons. Staring a repository gives it public endorsement, like upvoting it on social media. Sponsor Iinks off-site where you can buy me a beer. 😉
