### ISSUE TITLE
Installer seems not too clean

### ISSUE THREAD

**Issue by HerrZufall** [da2x/EdgeDeflector#102]
Hi!
I love the EdgeDeflector, but the Installer seems not too clean. Is there a way around?

https://www.virustotal.com/gui/file/7ea4b60b3ab640472f616ec56cd519bd1006ccd59f6be81b5d9e5e2c157f584b/detection

**Comment by da2x** [comment]
No, I can't do anything about third-party software such as antivirus. It used to be half of them, but the installer has gradually gained popularity and thus got a better reputation with antivirus vendors.

It detects the following line in the installer as malicious:
https://github.com/da2x/EdgeDeflector/blob/57b9fd02e96fdc270662d9cdd0bb3702bb213d74/EdgeDeflector/resources/nsis_installer.nsi#L55

You can evaluate this line of code yourself and decide whether you think it's malicious.
