### ISSUE TITLE
Feedback: Was unable to get to work even with Troubleshooting Steps

### ISSUE THREAD

**Issue by molitar** [da2x/EdgeDeflector#104]
I found a solution that worked though and I think should be added to your troubleshooting Wiki.

EdgeDeflector never asked me and just kept opening up Edge so I finally figured out a way to get this resolved every time.

Start > PC Settings > Apps > Default Apps > Set defaults by app > Scroll down to Edge > Manage > set the "MICROSOFT-EDGE" to EdgeDeflector. Done now it opens my Cortana Searches in my default browser.

**Comment by da2x** [comment]
This is the third option on the [troubleshooting page](https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting).

Would you mind uninstalling EdgeDeflector from Add & Remove Programs, and then trying [this updated installer](https://github.com/da2x/EdgeDeflector/files/6291296/EdgeDeflector_install.exe.zip). Does it work better? Is it easier to understand? Other feedback? Thanks!
