### ISSUE TITLE
Can't search from Start menu after installing EdgeDeflector

### ISSUE THREAD

**Issue by glibg10b** [da2x/EdgeDeflector#106]
Please follow the troubleshooting steps first!
https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting

**Done.**

---

**To Reproduce**
1. Install EdgeDeflector
2. Press Windows key
3. Start typing

---

**Expected behavior**
There should be multiple recommended search completions, e.g. when typing "why":
- "why do"
- "Why I"
- "why d"
- "why does"
- "why did the"
- "why do you think"
etc. 

---

**Actual behavior/describe the bug:**
These completions don't show up. When searching something long (e.g. why is the sky blue), it shows:
- No results found for 'why is the sky blue'

---

**Details:**
 - Windows version: **Version 20H2 (OS Build 19042.928)**
 - Windows 10 Pro N for Workstations

**Comment by da2x** [comment]
EdgeDeflector doesn't change anything related to how search works internally. It's literally just when links are opened that the program even runs.

Uninstall EdgeDeflector from Add and Remove Programs. Try the same steps again. You shouldn't notice any difference (other than which browser your links open in.)

**Comment by glibg10b** [comment]
You're right, neither uninstalling nor reinstalling fixed the problem. This is a 7-hours-old Windows install, and it worked fine the last time I checked before I installed EdgeDeflector, so I suspect it's [Windows10Debloater](https://github.com/Sycnex/Windows10Debloater) (which I ran right before it) which caused the problem.

**Comment by da2x** [comment]
Thank you for testing and confirming. I'll close this issue then.
