### ISSUE TITLE
Small feature request

### ISSUE THREAD

**Issue by klepp0906** [da2x/EdgeDeflector#107]
99.99% of the time this app is priceless.  I assume its only going to become even more valuable with time as this particular instance makes evident.

The new "news and interests" taskbar widget thing.  If you try to click "manage interests" it will redirect to your browser of choice.  The problem is, Microsoft has made it in such a way that you can not manage your interests unless you open that particular link in edge cause theyre awesome. 

A useful (but probably more labor intensive) feature would be the ability to omit certain links from being redirected.  Or even a toggle ala hotkey or something.

In general you can simply uninstall edgedeflector and set up your interests and reinstall it and carry on.   It just poses an inconvenience if you want to adjust down the road, nevermind any future obstacles microsoft will implement trying to force edge on us in the future.

Either way, just thinking aloud.   Thank you for app regardless.   I've been using it a long time and intend to continue to do so :)

**Comment by klepp0906** [comment]
also fwiw does not remove the openwith entry from registry (under filexts i believe) so upon reinstall it instantly starts opening with edgedeflector again as opposed to asking. 

may want to make it clean that on uninstall.

**Comment by da2x** [comment]
> The new "news and interests" taskbar widget thing. If you try to click "manage interests" it will redirect to your browser of choice. The problem is, Microsoft has made it in such a way that you can not manage your interests unless you open that particular link in edge cause theyre awesome.

Press Win+F to report the Microsoft bug to Microsoft. Also, please [file a Web Compat bug](https://webcompat.com/issues/new) about the page not working in non-Edge browsers.

> also fwiw does not remove the openwith entry from registry (under filexts i believe) so upon reinstall it instantly starts opening with edgedeflector again as opposed to asking.

Apps can no longer make any changes to user preferences set by the user. So this is up to Microsoft to fix, if you don’t like it persisting this settings.

**Comment by klepp0906** [comment]
both good pieces of information, thank you & thanks again for edgedeflector :)

**Comment by da2x** [comment]
Closing this as EdgeDeflector works as expected. MSN.com being broken should be handled directly by Microsoft or through webcompat. (You did login to MSN.com first in your default browser, right?)

**Comment by klepp0906** [comment]
I was logged in to my microsoft account there yes,  first thing i checked.   Also tried on another pc to verify the behavior.  The site works, its just absent the feature that allows you to "personalize" your news feed unless its done in edge.  I dont think its broken, i think its intentional by microsoft in an effort to further compel/force people to use edge. 

Nothing is wrong with edgedeflector persay, it would just be nice to somehow implement the ability to disable it without uninstalling it or blacklist certain link/urls from being redirected.

**Comment by mikhoul** [comment]
> i think its intentional by microsoft in an effort to further compel/force people to use edge.

Maybe you could try to change the UserAgent of your browser to Edge UA  for  msn.com.

There is many extensions that allow you to change the UA for specific websites.

**Comment by klepp0906** [comment]
thats a good idea actually.  I'll take a look into that thanks for the suggestion!
