### ISSUE TITLE
No option to choose edgedeflector for standard apps

### ISSUE THREAD

**Issue by tarifari** [da2x/EdgeDeflector#108]
Please follow the troubleshooting steps first!
https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting

**Expected behavior**
Edgedeflector in the list as an option for standart apps settings

**Actual behavior/describe the bug:**
I intalled edgedeflector many times, restarted, resetted my standart-apps, but i cant choose edgedeflector on the list where i can choose my standart browser.

Tried to change this by apps, but if i click on Edge, the list with different file-extensions opens up and there i cant choose edge-deflector too.

Im running out of ideas. Installed and uninstalled many times, no luck. Still cant choose edgedeflector

**Details:**
 - Windows version: 19042.985

**Comment by J3fftw1** [comment]
Hey, I struggled with the same thing before but you dont have to change the default browser.
![image](https://user-images.githubusercontent.com/44972470/118961579-c0f3bf80-b964-11eb-8e29-43e18aa08d68.png)
in that image at the bottom you can choose "Choose default apps be protocol". 
Then you search up "MICROSOFT-EDGE URL:microsoft-edge"
and select EdgeDeflecter

**Comment by J3fftw1** [comment]
No problem have fun avoiding edge

**Comment by hugozijlmans** [comment]
Maybe close this issue? Br.
