### ISSUE TITLE
Clicking on new Windows 10 21H1 Weather widget does nothing

### ISSUE THREAD

**Issue by LordBoos** [da2x/EdgeDeflector#109]
**To Reproduce**
1. Click on new Weather widget added in Windows 10 21H1 update
2. Click on weather card or any of the buttons on said weather card

**Expected behavior**
Microsoft Weather page would open in my default browser (Chrome).

**Actual behavior/describe the bug:**
Nothing happens, no page is opened. When I disable EdgeDeflector, weather pages properly open in Edge.

**Details:**
 - Windows version: Windows 10 Pro 21H1 19043.1023

**Comment by parcox** [comment]
I encountered the same problem here.

**Comment by trungking** [comment]
same for me

**Comment by Etaboada95** [comment]
same problem 😢

**Comment by da2x** [comment]
I’m investigating.

**Comment by da2x** [comment]
Resolved by commit 49477b3b1b89c5da477a6a437b8f8a1a639196b9. New version coming up shortly.
