### ISSUE TITLE
Windows 10 Creator's Update?

### ISSUE THREAD

**Issue by NovaViper** [da2x/EdgeDeflector#11]
Hey are you going to patch this for the Creator's Update? I just received the notification to upgrade to it but I set it for later as I'm not sure what the changes would do this program and many other ones.

**Comment by da2x** [comment]
I'm not aware of any problems specific to this update. However, as stated in the readme file: “You may need to [reinstall EdgeDeflector] after installing major feature updates to Windows through Windows Update.”

**Comment by NovaViper** [comment]
Ah ok, whenever I get the notification again and update my pc, i'll test out the program and see if there are any problems

**Comment by NovaViper** [comment]
It works, the update didn't affect the functionality of Edge Deflector
