### ISSUE TITLE
When using edge-deflector still Bing in Chrome is used as default search engine

### ISSUE THREAD

**Issue by hugozijlmans** [da2x/EdgeDeflector#110]
My default search engine in Chrome is google, however using edge-defletor even though the search is now opening in Chrome it will still use Bing search.

**Comment by da2x** [comment]
https://github.com/da2x/EdgeDeflector/blob/8cd2aff9f7ff00f6e73022b80633fac7e448c327/README.md#will-searches-inside-cortana-still-use-bing

**Comment by hugozijlmans** [comment]
> https://github.com/da2x/EdgeDeflector/blob/8cd2aff9f7ff00f6e73022b80633fac7e448c327/README.md#will-searches-inside-cortana-still-use-bing

Thanks.
