### ISSUE TITLE
Edge deflector silent install???  can you make it possible?

### ISSUE THREAD

**Issue by kilaueaPC** [da2x/EdgeDeflector#113]
Please follow the troubleshooting steps first!
https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting

**To Reproduce**

**Expected behavior**

**Actual behavior/describe the bug:**
A clear and concise description of what happen instead.

**Details:**
 - Windows version: (Press Win+R, type `winver`, and include the full version number)

**Comment by BinToss** [comment]
Edge Deflector uses an NSIS installer, so...
https://nsis.sourceforge.io/Docs/Chapter3.html#installerusagecommon
![image](https://user-images.githubusercontent.com/7243190/130607632-4241e371-a684-49b4-b591-da4c1ad06952.png)

**Comment by da2x** [comment]
It won’t be silent, though. It will still open the post-install page and ask you to manually change the protocol handlers.
