### ISSUE TITLE
Downloads but will not execute

### ISSUE THREAD

**Issue by Puerua** [da2x/EdgeDeflector#119]
I'm a novice.
EdgeDeflector is a great idea. Thanks
I have downloaded the file, but install will not run. Is there anything different about this file that makes its installation different from usual installations? I am running in Windows 10 and trying to manage the issue!

**Comment by da2x** [comment]
Please describing in detail what you've done and tried, and what happens at each step along the way. Then I'll be better able to help you.

**Comment by Puerua** [comment]
Hi Daniel:
I will do.
I just wanted to acknow6eldge your quick reply and let you know that I shall be doing so in a few hours.
Thanks.

   W Noel Brown  
TH122 / 1 Lady Isaac Way
Mairehau, Christchurch 8052
NEW ZEALAND

 

    On Saturday, June 19, 2021, 10:29:37 PM EDT, Daniel Aleksandersen ***@***.***> wrote:  
 
 


Please describing in detail what you've done and tried, and what happens at each step along the way. Then I'll be better able to help you.

**Comment by Puerua** [comment]
Hi Daniel:
I have managed to run your app, tho I am not completely sure how I did so. 

But FYI, in case it helps you in any way.
I am running Windows 10 Home edition Version 2004 OS build 19041.1052 With Windows Experience Pack 120.2212.2020.0
My last quality update was KB5003637, installed 6/11/2021. For a x64-based system.
I had not been having problems with other downloads, prior to my attempt to down EdgeDeflector. The day before I had downloaded (from the web) a copy of Corel Photoshop Pro and it executed and opened properly.

Re EdgeDeflector - I read a description on the net, and it seemed to me that it might help me with the problem I have been having with broken links followed the latest MS version of Windows 10. The issue was a problem if my machine crashed, and I had to restart it (not reboot, that seemed not to cause a problem.).
From GitHub - and on that first attempt at downloading I was not a registered user (could that have caused a problem?), I was able to down load your executable file. Off my top bar where downloads sit, I could run not the app by double-clicking.
I then went to my download folder on my hard-drive, the file was there. Again I could not activate it.
I returned to the GitHub site, and this time I signed up and logged in. I then downloaded the app again. This time when I clicked on the downloaded file and nothing happened I went to downloads, and this time the file executed.
After that my recollection gets muddled. I think I was surprised the app had actually opened. The next thing I knew I as looking at your page - Manual setup steps.I followed your steps, and selected ED in the Windows setting with the Edge..
I could not change MS Edge Holographic. I figure that may not be necessary for me. I tried but was not successful.
When I checked (as per your double-check) I was taken back to the GitHub home page.

I did a total reboot of the machine this morning. ED was still in place when the machine finally booted up fully.

The machine was very very slow when I restarted it. This seems to always be true when I have done something affecting the operating system. I have had to restore some links this morning but it has been quicker to do so this time. It is also possible that restarting the machine a 2nd time will mean the system finds the changes ED has made are still in place,the start will be faster, and the links will be OK. That is what I am hoping anyway. I shall let you know if you wish.
Again, thank you for writing the app. I suspect that, like a lot of people around the world I really appreciate your expertise and time.
Best wishes.
Noel

   W Noel Brown  
TH122 / 1 Lady Isaac Way
Mairehau, Christchurch 8052
NEW ZEALAND

 

    On Saturday, June 19, 2021, 10:29:37 PM EDT, Daniel Aleksandersen ***@***.***> wrote:  
 
 


Please describing in detail what you've done and tried, and what happens at each step along the way. Then I'll be better able to help you.
