### ISSUE TITLE
Instruction only shows in Edge

### ISSUE THREAD

**Issue by Heinzip** [da2x/EdgeDeflector#120]
Hi, opening the instruction after installation in Edge is not recommended. When you want to avoid Edge or already deinstalled it, it would make more sense to open the instruction with the current default browser.
Anyway a nice program. Thanks.

**Comment by da2x** [comment]
Hi, the instructions are only needed if the post-installation page automatically opens in Edge instead of in your preferred web browser.

**Comment by da2x** [comment]
I’ve added a button to reveal the instructions in other browsers.
