### ISSUE TITLE
Launch `ms-settings:defaultapps` during setup

### ISSUE THREAD

**Issue by NatoBoram** [da2x/EdgeDeflector#122]
> ## Manual setup steps
> 
> Please follow these steps to complete your installation of EdgeDeflector. (Sorry, Windows refuses to let this be automated during the installation!)
> 
> 1. Open the [Windows Settings](ms-settings:) app.
> 2. Go to [Apps](ms-settings:appsfeatures): [Default apps](ms-settings:defaultapps).

Step `#2` could be automated by launching `ms-settings:defaultapps`. The [website](https://www.daniel.priv.no/tools/edgedeflector/post-install.html) could also have a link to `ms-settings:defaultapps`.

Docs : https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app#apps

**Comment by da2x** [comment]
That wouldn't help, though. People wouldn't know what to do in the window if it opened all by itself without context.

Linking to the `ms-settings:` from the web can be problematic. Web browsers will either show a scary warning message, ask the user to choose what application to use to open the link, ignore the click entirely, or open the Settings app. It can be a good experience, but it may also be bad depending on many factors.

The links can't deep-link to the correct screen in the Default apps section.

**Comment by NatoBoram** [comment]
I think leaving it on the `Default apps` is good enough then. If someone fails to click on it or to click on "next" when asked to select an app, they can always manually open Settings. It would particularly come in handy if someone has already performed these steps once and already know what to do.
