### ISSUE TITLE
Cannot install on Windows 10 Enterprise

### ISSUE THREAD

**Issue by mruac** [da2x/EdgeDeflector#123]
**To Reproduce**
1. Download the latest version
2. Open the executable file
3. Windows system error: "This app can't run on your PC. To find a version for your PC, check with the software publisher." 

**Expected behavior**
Able to install and redirect windows search results to chrome.

**Details:**
Windows 10 Enterprise (OS Build 18363.1621)
Lenovo thinkpad laptop is company issued.

**Comment by da2x** [comment]
Do you get any more information in that dialog?

**Comment by mruac** [comment]
I'm not able to take a screenshot of the dialog now but this is pretty much the dialog.
![image](https://user-images.githubusercontent.com/19784752/125423737-886d8835-f923-41a0-94b0-dc661e1ef29d.png)

**Comment by J3fftw1** [comment]
Doesn't your company have rules on what can be installed and not?

**Comment by mruac** [comment]
Not necessarily, just as long it is not against their policies. Because of this, I am free to install anything I'd like if it improves my workflow. I'd share a screen recording but they have rules in place to prevent uploading data.

**Comment by da2x** [comment]
This is something you need to ask your IT team about. I can't guess at what policies they have in place.

**Comment by mruac** [comment]
I'll close this issue because I was able to install [SearchDeflector](https://github.com/spikespaz/search-deflector) instead.
