### ISSUE TITLE
3 security vendors flagged this file as malicious

### ISSUE THREAD

**Issue by crius-al** [da2x/EdgeDeflector#125]
https://www.virustotal.com/gui/file/3b1cb1e9a8187e16f6447b81785632fa5989d72a0475d82390ba52448a5defa5/detection is worrisome. This is the 
EdgeDeflector version 1.2.2.0 Latest
on Jun 10

**Comment by da2x** [comment]
This is a duplicate of issue #116. Please see the discussion there.
