### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by Shadow0013HUN** [da2x/EdgeDeflector#126]
Hi there,

So the program didn't do anything that it was supposed to do, therefore I wanted to uninstall this bloatware from my computer, and I am not willing to set up that list again from scrap because of a reset. 
However, when I clicked uninstall in Settings/Apps/EdgeDeflector, a window popped up for me to select what program to open the file with. And I was like WTF.

So please help me uninstall the latest version of EdgeDeflector, because I hate bloatware. It was installed to default path.
Thank you for you help.

**Comment by da2x** [comment]
I'm not going to help you because you're rude.

**Comment by Shadow0013HUN** [comment]
> I'm not going to help you because you're rude.

I'm not rude. I simply stated facts. So, how does one uninstall this?
