### ISSUE TITLE
Unable to uninstall EdgeDeflector

### ISSUE THREAD

**Issue by Shadow0013HUN** [da2x/EdgeDeflector#127]
Hi there,

Because I was just deflected by the dev, I created another ticket, hoping this time, he won't be this rude and disrespectful towards me.

So the program didn't do anything that it was supposed to do, therefore I wanted to uninstall this turn out bloatware from my computer, and I am not willing to set up that list again from scrap, that was proposed as a supposed fix.
However, when I clicked uninstall in Settings/Apps/EdgeDeflector, a window popped up for me to select what program to open the file with. And I was like WTF.

So please help me uninstall the latest version of EdgeDeflector. It was installed to default path.
Thank you for you help.

NOTE: I will keep making tickets until you properly respond to me, and solve my issue that you have created.

**Comment by TheBooker66** [comment]
@Shadow0013HUN that's not bloatware dude. bloatware is when something comes preinstalled on your computer before you buy it. also, he was disrespectful because you were first, calling his program useless and bloatware.
