### ISSUE TITLE
**Just works** upgrading to windows 11 (21H2 8/‎15/‎202 build 122000.132 Windows Feature Experience Pack 1000.22000.132.0)

### ISSUE THREAD

**Issue by mxsocks** [da2x/EdgeDeflector#128]
continues working exactly as expceted on a windows 10 home install (fully updated as of 8/14/2012) upgraded to windows 11 (version in title)

No manual intervention has been necessary so far (8/15 to 8/21/2021) - Windows 11 has respected my Windows 10 settings with regard to the default browser with every interaction, and everything that has opened in a browser has opened in my Windows 10 default.

**Comment by da2x** [comment]
Thank you for the feedback.
