### ISSUE TITLE
[Feature request/Question] Is it possible to use edge deflector to make chrome links open with my browser of choice?

### ISSUE THREAD

**Issue by ItsCubeTime** [da2x/EdgeDeflector#129]
Hi there! So I use the web version of Discord (a social networking app) due to a bug in the desktop version - and its working great in general.

Its just that I use Opera GX as my default and prefered browser but open Discord in Chrome to avoid having other tabs open in the same window as I have Discord open in. But this of course makes it so any links I press within the client will also open up with Chrome.

Can I avoid this somehow? Is this something a modified version of EdgeDeflector might help with? Any ideas/troubleshoot steps would be appreciated <3

![image](https://user-images.githubusercontent.com/20190653/130569752-45f8e6ff-886e-4106-b64d-0897245a66c8.png)

**Comment by BinToss** [comment]
EdgeDeflector doesn't touch the browsers at all. What you're asking for would require modifying Chrome itself. 
Perhaps a Chrome extension that adds "Open link with..." to the context menu would be a more suitable solution than expanding the scope of EdgeDeflector.

**Comment by da2x** [comment]
This is out of scope for EdgeDeflector.

What you need is for Discord to support installing their website as a PWA and for that PWA to support https://web.dev/pwa-url-handler/
