### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by Timmmm** [da2x/EdgeDeflector#13]
Unfortunately this seems to not work. Start menu searches still open in Edge after installing it.

Perhaps Microsoft "fixed" this in the Creators Update.

**Comment by da2x** [comment]
No, it still works but you may have to reapply your settings after installing major updated to Windows. Microsoft resets the list of default programs after large updates, which may unset your default browser and also remove EdgeDeflector.

See the [installation notes](https://github.com/da2x/EdgeDeflector/blob/master/README.md#installation).

**Comment by Timmmm** [comment]
I'm using it for the first time. Are you saying it works for you even with the Creators Update?

**Comment by da2x** [comment]
Yes, and it has been confirmed by others to work as well. Read the installation notes carefully for troubleshooting tips.

**Comment by Timmmm** [comment]
Huh weird, I just tried it again after uninstalling it and it worked first time. I literally did nothing different:

1. Install
2. Start->Search for something -> Opens in Edge
3. Manually run `C:\Program Files (x86)\EdgeDeflector\EdgeDeflector.exe` - maybe that does something.
4. Still opens in Edge.
5. Run installer again.
6. Still opens in Edge.
7. Give up, run EdgeDeflector_uninstall.exe

--- next day ---

1. Ok I'll try once more. Run installed.
2. Start->Web search. "Open with" dialog!

Maybe worth adding "If it really doesn't work try uninstalling it and installing again." or something to the readme.

**Comment by da2x** [comment]
That sometimes happen when the default app association database is corrupt. It’s a Windows issue.

I’m sorry about this being difficult to use, but I can only do so much to work around Windows muck.

**Comment by Timmmm** [comment]
Yeah no worries, thanks for making this!

**Comment by spryh** [comment]
Had same problem. System Settings/Default Apps/Reset to Microsoft Recommended ... and try again. It works. Thanks again!
