### ISSUE TITLE
Request to make Https the default fallback

### ISSUE THREAD

**Issue by superfawkes** [da2x/EdgeDeflector#133]
Reasons:
* the bulk of the URLs intercepted from the OS are https.
* Most browsers have fallback mechanisms to warn and load http as needed. This warning has utility.
* extensions like https-only may see the http call, even if the URI redirect supports https, and issue over-zealous warnings.

**Comment by da2x** [comment]
This change would break links to devices on the local network. It could also break captive portals (WiFi login pages).

Some web browsers have begun redirecting http: links to https:, but they try to avoid redirecting pages that must be opened with http: (such as your router set up page). They've got more information about which origins should and shouldn't be directed.  I prefer deferring this decision to the Web browser as it's better suited to make the right one.
