### ISSUE TITLE
Doesn't work with Windows 10 Twitter app

### ISSUE THREAD

**Issue by CubsWin1** [da2x/EdgeDeflector#134]
I have installed EdgeDeflector and verified that it is working, but the Windows 10 Twitter app still opens links in Edge.  Is it possible to change the behavior of links in the Twitter app as well?

**Comment by da2x** [comment]
The Twitter app is an installed webapp. It's running inside a reskinned version of Edge. There's nothing EdgeDeflector can do about this.

You can uninstall the Store version and install it via your favorite web browser instead. (Installable webapps aren't supported by Firefox.)

You should also open the Windows Feedback app, and complain to Microsoft about the unwanted behavior.
