### ISSUE TITLE
EdgeDeflector leaves ghost program on the Default Apps menu.

### ISSUE THREAD

**Issue by cincovp** [da2x/EdgeDeflector#138]
**To Reproduce**
Simply uninstall EdgeDeflector

**Expected behavior**
EdgeDeflector gets successfully uninstalled.

**Actual behavior/describe the bug:**
EdgeDeflector leaves a ghost and iconless "Microsoft Edge" in the browser tab on the Default Apps menu in the settings app

**Details:**
Windows 10 21H1 - Build Version 19043.1237

![kA3ei6W](https://user-images.githubusercontent.com/53921095/135900983-df055267-c9a2-4a27-be1b-f3b8696ea613.png)

**Comment by da2x** [comment]
No, that's one on Microsoft.
