### ISSUE TITLE
Stopped working wit Build 16241

### ISSUE THREAD

**Issue by Mronsani413** [da2x/EdgeDeflector#14]
Hey, I've been using ED for months through various insider builds but it seems to have stopped working with insider build 1624. When selected it will just stop responding. 
![capture](https://user-images.githubusercontent.com/30231614/28264161-addfff94-6ab7-11e7-8c83-9fa62b28aa1b.PNG)

**Comment by da2x** [comment]
Hi, thank you for reporting this! Could you please go to the Windows Reliability Monitor (search for “reliability monitor” in Start), find EdgeDeflector in the list of problems, double-click on it, and copy the problem details into this bug. This will let me know more about what might have gone wrong.

**Comment by Mronsani413** [comment]
Sure, no problem. I will do it as soon as I get home from work today.

**Comment by Mronsani413** [comment]
![ed](https://user-images.githubusercontent.com/30231614/28291222-8ec83706-6b17-11e7-9143-c83a079a210e.PNG)

**Comment by da2x** [comment]
Thank you, @Mronsani413. I do indeed not handle `System.UriFormatException` in EdgeDeflector. I’ll look into that. However, I’d really appriciate more information about the problem as I haven’t been able to reproduce the issue myself yet.

Please press Win+R, paste in the following, and press Enter:

    microsoft-edge:https://example.com

Does that crash EdgeDeflector? If not, then where are you following links that leads to EdgeDeflector crashing? Is it from within Cortana? What types of links?

**Comment by Mronsani413** [comment]
It does not. It seems to work except when I use cortana to bring up a website or search the web. So if i hit the windows key and type in 'amazon.com', I will get the crash notifications.

**Comment by Mronsani413** [comment]
If i do any searching from Cortana or the Dialog box, it will crash. I had rolled back to the previous insider update last night, 16238 or something like that, and the problem went away. I reinstalled 16241 this morning and the issue came back.

**Comment by tip2tail** [comment]
Hello @Mronsani413  and @da2x 

I too was having this issue however I have forked this repo and fixed it myself now.

See PR #15 .

Hope this helps :)

t2t

**Comment by da2x** [comment]
This helps a lot! I’ve been away on vacation so haven’t had the time to work on this. I’ll get a new version out within a few days.

**Comment by da2x** [comment]
Resolved by pull request #15 and commit 57c711413e.

**Comment by da2x** [comment]
Fixed in [version 1.1.1.0](https://github.com/da2x/EdgeDeflector/releases/tag/v1.1.1.0).
