### ISSUE TITLE
edge icon showing instead of chrome icon on windows search(minor issue)

### ISSUE THREAD

**Issue by yazan1107** [da2x/EdgeDeflector#140]
Please follow the troubleshooting steps first!
https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting

**To Reproduce**
1. open search windows(windows+s/windows+q)
2.search for any website(e.g. google.com)
3. Scroll down to web results
4. See error icon is for edge browser instead of chrome icon, i wish u can fix this minor issue!

**Expected behavior**
chrome icon instead of edge icon
**Actual behavior/describe the bug:**
A clear and concise description of what happen instead.
edge icon in websearch result
**Details:**
 - Windows version: (Press Win+R, type `winver`, and include the full version number)
21h2 build 22000.282

**Comment by rampageX** [comment]
[Rebuild Icon Cache in Windows 11/10](https://www.thewindowsclub.com/rebuild-icon-clear-thumbnail-cache-windows-10)

**Comment by yazan1107** [comment]
i think it is not a bug

> [Rebuild Icon Cache in Windows 11/10](https://www.thewindowsclub.com/rebuild-icon-clear-thumbnail-cache-windows-10)

i think it is not a bug, but a missing feature.

**Comment by osyu** [comment]
UWP search is hardcoded to use Edge's icon, not the icon currently associated with the microsoft-edge URI, so there isn't really any way to prevent this other than replacing Edge's own icon itself.
