### ISSUE TITLE
Update docs so people get aware of existing Edge settings to resolve it

### ISSUE THREAD

**Issue by rokonec** [da2x/EdgeDeflector#142]
Although this tools has many use cases, the most common uses cases, such as clicking on link in Teams, could be solved this way:

>If you would like Teams to use the system default browser instead,
>- Open the Edge browser, select Settings and then select Profiles
>- Under Profiles go to Profile Preferences
>- Turn off “Use Microsoft Edge to open links from other Microsoft apps”

Please consider to put this into your documentation/readme so people can discover it.

**Comment by da2x** [comment]
Okay, so this is interesting. However, I’m not seeing this option in any combination of either Microsoft Edge, Windows 10, or 11. Nor are there any other mentions of it on the web. It doesn’t appear to be a normal option with general availability.

What versions of everything are you using? Is it a special enterprise managed device? You seem to be a Microsoft employee, so you may be using a special internal build with unreleased features of something?

**Comment by rokonec** [comment]
Let me check. Looks quite standard `Edge` to me.

![image](https://user-images.githubusercontent.com/25249058/141754733-b6e471c7-feb0-4fe9-bb8c-e53fc72d0580.png)

![image](https://user-images.githubusercontent.com/25249058/141754843-53808181-e0ac-4830-97e1-6c4dd795ea20.png)

**Comment by da2x** [comment]
I don’t see that checkbox in Windows 10 or 11; home or pro; with one or two profiles; with or without a linked Microsoft Account. Hm. I uploaded your screenshot to Yandex Image Search and it only found other variations of that setting screen without that checkbox. Instead of that option, most people see the “Allow single sign-on for work or school sites using this profile” option in its place. So, I don’t know what’s needed to make it show up. It’s not documented nor talked about anywhere either.

**Comment by da2x** [comment]
The checkbox is only displayed if `enhancedLinkOpeningEnabled` is true. The flag isn’t exposed through a command line argument nor in edge://flags, so I don’t know what controls it. It could be a group policy? or some extension or software you’ve installed?

**Comment by ZaLiTHkA** [comment]
_completely off-topic_, since I have little-to-no interest in Win11 myself, but after reading this..

> I don’t see that checkbox in Windows 10 or 11; home or pro; with one or two profiles; with or without a linked Microsoft Account. Hm. I uploaded your screenshot to Yandex Image Search and it only found other variations of that setting screen without that checkbox. Instead of that option, most people see the “Allow single sign-on for work or school sites using this profile” option in its place. So, I don’t know what’s needed to make it show up. It’s not documented nor talked about anywhere either.

..I just had to drop a quick note to say: @da2x the extent to which you go in debugging things like this is nothing short of incredible! 👍🏼
