### ISSUE TITLE
Edge is the best browser

### ISSUE THREAD

**Issue by Pedro1234-code** [da2x/EdgeDeflector#143]
Edge is the best browser. I don't know why people hate Edge. Edge have a lot of features like vertical tabs, sleeping tabs, collections, and many other things. Microsoft want people to use Edge like Google want people to use Chrome. Edge is lighter and faster than Chrome. Windows have Edge as default and Chrome OS and Android have Chrome as default. It's completely normal. Give a chance for Edge Chromium. You can't search on Chrome OS Android using system using default browser so create a ChromeDeflector for Android and Chrome OS.

**Comment by djhenderson** [comment]
Irrelevant. When I specify a preferred browser, I expect that preference to be honoured by **absolutely** everything that needs to browse the internet.

**Comment by Pedro1234-code** [comment]
Google does the same thing. Create a ChromeDeflector. Give a chance for Edge.

**Comment by Tkain** [comment]
Irrelevant discussion. Can we close this?

**Comment by AzAgarampur** [comment]
What are you trying to prove by claiming "Edge is the best browser?" This is your opinion, and it completely off topic to this repo. If you wanna use Edge, then why're you looking here?

> Microsoft want people to use Edge like Google want people to use Chrome.

There's a difference between Microsoft using it's monopoly and forcing people to use Edge and Google wanting people to use chrome.

**Comment by gumbarros** [comment]
Edge is a good browser. Force edge in users throat is wrong. Close the issue.

**Comment by Pedro1234-code** [comment]
@AzAgarampur Say me. What is Microsoft doing on Windows that Google isn't doing in their systems?

**Comment by D0nnieD4rk0** [comment]
we've a smartass on our hands

**Comment by AzAgarampur** [comment]
> What is Microsoft doing on Windows that Google isn't doing in their systems?

1. Forcing edge (duh)
2. Reinstall edge whenever you get a feature update
3. Edge popups all over the system
4. Introducing an encrypted URL handler to prevent browser wars
5. Changing internal API's to be callable from edge only.

Need I same more?
