### ISSUE TITLE
what is MICROSOFT-EDGE-HOLOGRAPHIC? any why there is no option to choose edge deflector?

### ISSUE THREAD

**Issue by yazan1107** [da2x/EdgeDeflector#147]
Please follow the troubleshooting steps first!
https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting

**To Reproduce**
1. Go to '...'settings
2. Click on '....'default apps by protocol
3. Scroll down to '....'MICROSOFT-EDGE-HOLOGRAPHIC
4. See error no edge deflector

**Expected behavior**

**Actual behavior/describe the bug:**
A clear and concise description of what happen instead.

**Details:**
 - Windows version: (Press Win+R, type `winver`, and include the full version number)

**Comment by da2x** [comment]
It's only for Hololens. There are no links actually using this in Windows.

**Comment by Andrei12333** [comment]
I had the same issue, See it at #156
