### ISSUE TITLE
EdgeDeflector isn't on the application list

### ISSUE THREAD

**Issue by thepwrtank18** [da2x/EdgeDeflector#148]
**To Reproduce**
1. Install EdgeDeflector
2. Follow instructions on screen
3. Try to change Microsoft Edge to EdgeDeflector
4. EdgeDeflector isn't on the list

**Expected behavior**
EdgeDeflector was an option

**Actual behavior/describe the bug:**
Only Edge shows up as an option

**Details:**
Windows 11 22000.346

**Comment by da2x** [comment]
Duplicate of #141.
