### ISSUE TITLE
cannot change to Edge Deflector on default applications by protocol

### ISSUE THREAD

**Issue by dtantono** [da2x/EdgeDeflector#151]
Please follow the troubleshooting steps first!
https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting

**To Reproduce**
1. Go to https://github.com/da2x/EdgeDeflector/releases/tag/v1.2.3.0
2. Click on Setting
3. Click on Apps
4. go to  default apps
5. scroll down to default applications by protocol
6. Find MICROSOFT-EDGE
7. I cannot change to default applications by protocol

**Expected behavior**
I cannot change to default applications by protocol

**Actual behavior/describe the bug:**
I cannot change to default applications by protocol

**Details:**
 - Windows 10 version 21h2 OS Build 19044.1387
<img width="726" alt="Screenshot 2021-11-23 143018" src="https://user-images.githubusercontent.com/29157187/142975889-7e824ad1-7964-4212-968a-7db761abb445.png">

**Comment by FluffBallFloof** [comment]
Same issue for me, also on 21H2.

**Comment by iskandarluqman** [comment]
I can confirm that I am having the exact same issue on Windows 10 version 21H2 with OS Build 19044.1387

**Comment by sturdy-cactus** [comment]
confirm, same issue.

**Comment by designatedcoder** [comment]
Same for me.  I tried resetting everything back to default settings then did a clean install of deflector.  Still won't let me change it.

**Comment by meek2100** [comment]
Duplicate of #141?

**Comment by dtantono** [comment]
@meek2100 that one is for Win11 and this one is for Win10

**Comment by 1to5pc** [comment]
MS is breaking the functionality of this app. :(

**Comment by dtantono** [comment]
Since win10 and win11 are not really the same OS. I hope MS does not synergise the win11 policy to win10.

**Comment by 1to5pc** [comment]
> 

If they feel want to (there is a high chance they will) they might push the policy to win 10 as well

**Comment by da2x** [comment]
Duplicate of #141.

**Comment by dtantono** [comment]
@da2x Windows 11 and Windows 10 is not same OS. Why close it?

**Comment by Briareos-A** [comment]
Because #141 has a [solution](https://github.com/da2x/EdgeDeflector/issues/141#issuecomment-997438087) to this problem. 

[MSEdgeRedirect](https://github.com/rcmaehl/MSEdgeRedirect)
