### ISSUE TITLE
Edge Deflector not working on Windows 10

### ISSUE THREAD

**Issue by LunaticBFF57** [da2x/EdgeDeflector#154]
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Choose default applications by protocol
2. Click on 'MICROSOFT-EDGE'
3. See the error

**Expected behaviour**
I expect to see the Edge Deflector application.

**Actual behaviour/describe the bug:**
The Edge Deflector application is not on the list.

**Details:**
Microsoft Windows
Version 21H2 (OS Build 19044.1387)
Windows 10

**What I See:**
![Screenshot 2021-11-30 113702](https://user-images.githubusercontent.com/78350612/143964534-fc386d88-ae10-4db9-abfd-d209577bbab9.png)

**Extra Notes**

It had worked before but had unexpectedly stopped working.

**Comment by LunaticBFF57** [comment]
The title should be: Edge Deflector not working on Windows 10
Sorry

**Comment by sudological** [comment]
I uninstalled the KB5007253 "Optional Quality Update" and that fixed the issue. This 'quality update' was likely the same thing Windows 11 recently did to disable Edge Deflector.

**Comment by LunaticBFF57** [comment]
When I uninstalled the update, Edge Deflector works again.

**Comment by LunaticBFF57** [comment]
When I uninstalled the update, Edge Deflector works again.
