### ISSUE TITLE
Redirect Besides Default Browser?

### ISSUE THREAD

**Issue by furqaanshamsi** [da2x/EdgeDeflector#16]
Is there a way to make EdgeDeflector redirect to a specific application? For example, what if I don't want it to redirect to Vivaldi? What if I want it to redirect to "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe -incognito" or something similar?

**Comment by da2x** [comment]
No, EdgeDeflector is designed to enforce the default browser option. This isn’t something I want to add either.

You are, however, free to modify EdgeDeflector to do whatever you want under the project’s permissive [license](https://github.com/da2x/EdgeDeflector/blob/459f2571c1/LICENSE).

Instead of opening the URL with the default browser, you could modifying [this block of code](https://github.com/da2x/EdgeDeflector/blob/459f2571c1/EdgeDeflector/Program.cs#L174-L179) and set the path to your preferred program or command as the `FileName` and pass the `uri` variable as an [`Argument`](https://msdn.microsoft.com/en-us/library/system.diagnostics.processstartinfo.arguments(v=vs.110).aspx) to that program or command. That is all it would take to do just what you want.

**Comment by furqaanshamsi** [comment]
Ah, thanks a lot for the info! It's helpful, but I'm just starting to get
confused now. I've never really dealt with C# (or programming in general
besides some C/C++, and markup like HTML), so I'm getting kind of confused.
Would I pass it, for example, as a string value like

FileName = "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe
-incognito"

And if so, how would I pass the URL as an argument for chrome after -incognito
? Sorry if I'm asking a dumb question, but I'm simply curious and the
reference you linked on ProcessStartInfo.Arguments didn't really make much
sense to me.

**Comment by da2x** [comment]
Start by [uninstalling EdgeDeflector](https://github.com/da2x/EdgeDeflector/wiki/Uninstall). You don’t want two conflicting copies to confuse things. Then download and install [Visual Studio Community](https://www.visualstudio.com/downloads/) edition (no cost), grab and unzip [the code](https://github.com/da2x/EdgeDeflector/archive/master.zip), open `EdgeDeflector.sln` in Visual Studio, modify `Program.cs` as instructed above, and click Build (somewhere up in the top menus). Copy the executable from the `EdgeDeflector/bin/Release` directory to somewhere on your system where you won’t delete it like `c:/Program Files/`. Then double-click and run the executable once to self-install it in the location where you copied it to. (Don’t delete the executable.)

Oh, and here is the change you need to make in full:

    ProcessStartInfo launcher = new ProcessStartInfo()
    {
        Arguments = "-incognito " + uri,
        FileName = "C:/chrome.exe",
        UseShellExecute = true
    };
    Process.Start(launcher);

Best of luck!

**Comment by furqaanshamsi** [comment]
WOWWW!! Thanks a lot! I'm such an idiot that I forgot about the very concept of concatenation haha

By the way, couldn't I do something similar? Instead of Arguments couldn't I do FileName = "C:/chrome.exe -incognito " + uri instead?

**Comment by da2x** [comment]
> WOWWW!! Thanks a lot!

You’re welcome. If you’ve appreciated this highly personalized tutoring experience, you can [send me all of your money](https://www.paypal.me/Aleksandersen/40usd). 🙃 

> nstead of Arguments couldn't I do […]

No, you can’t. It will be treated as one weird file name including spaces and arguments. (This is a security feature.) You have to pass it as an argument explicitly. The previously linked documentation has more … uhm … documentation on the subject.

**Comment by furqaanshamsi** [comment]
Ah lol I would donate but I'm not in college yet and I don't have a PayPal or bank account, but I see what you mean by "security feature" since it'd be bad if we could accidentally send/execute a program with parameters.

Thanks for these tidbits, I really appreciate it! 😃

On Aug 1, 2017, Daniel Aleksandersen <notifications@github.com> wrote:
>> WOWWW!! Thanks a lot!
>
>You’re welcome. If you’ve appreciated this highly personalized tutoring
>experience, you can [send me all of your
>money](https://www.paypal.me/Aleksandersen/40usd). 🙃 
>
>> nstead of Arguments couldn't I do […]
>
>No, you can’t. It will be treated as one weird file name including
>spaces and arguments. (This is a security feature.) You have to pass it
>as an argument explicitly. The previously linked documentation has more
>… uhm … documentation on the subject.

-- Sent with K-@ Mail - the evolution of emailing.
