### ISSUE TITLE
No funciona, creo que es por que desinstale edge de mi PC

### ISSUE THREAD

**Issue by kreislerramirezmt** [da2x/EdgeDeflector#162]
**To Reproduce**
(Spanish)
1. Presiono la tecla de windows
2. Escribo cual cosa
3. Presiono la tecla enter
4. Y no me redirecciona a mi navegador predeterminado

**Expected behavior**

**Actual behavior/describe the bug:**
Yo desinstale microsoft edge de mi windows, puede que eso lo haya cuasado.
![image](https://user-images.githubusercontent.com/91885759/146477884-cbc11f14-8a61-47ee-a4ee-1cecb6af5775.png)

**Details:**
 - Windows version: 2004 (Compilacion SO 19041.1237)

**Comment by da2x** [comment]
English only, sorry.
