### ISSUE TITLE
Windows 10 stopped working

### ISSUE THREAD

**Issue by Draghmar** [da2x/EdgeDeflector#165]
It looks like after recent update Win10 also blocks your app and forces to use Edge. :/

**Comment by charakaSamawry** [comment]
ffs just found the same as well

**Comment by charakaSamawry** [comment]
'select an program to open this in' dialog comes up and your choices are edge or edge or search microsoft store for edge

**Comment by charakaSamawry** [comment]
https://www.techworm.net/2021/12/update-edgedeflector-windows-10-11.html

https://github.com/rcmaehl/MSEdgeRedirect

**Comment by Draghmar** [comment]
Yup, using that other app makes URLs go to my FF. Thanks!
