### ISSUE TITLE
No Edge Deflector default: Windows 10 Build 19042.1415

### ISSUE THREAD

**Issue by deathhancox** [da2x/EdgeDeflector#167]
Having an issue on Windows 10 Build 19042.1415 where edge deflector doesn't show up as an option for the MICROSOFT-EDGE protocol. I've tried resetting my defaults, reinstalling edge deflector, and restarting my pc to no effect. This also completely prevents it from redirecting to my preferred browser.

![Evidence](https://user-images.githubusercontent.com/35537156/147375033-5164a9ea-c874-4ec8-952a-a145670ed88c.PNG)

**Comment by Zenphia** [comment]
Same issue on 19044 (21H2)

**Comment by sgolub** [comment]
Also impossible to do that from "Set defaults by app" page

![image](https://user-images.githubusercontent.com/2202453/147414658-9d0c2819-0ff9-43e7-b4a4-5ca6e1c7afc6.png)

**Comment by da2x** [comment]
Duplicate o# #141.
