### ISSUE TITLE
Could this be adapted (or used) to intercept *all* URI/URL open attempts?

### ISSUE THREAD

**Issue by earthbound19** [da2x/EdgeDeflector#17]
It annoys me when any process or application presumes to just open a browser session to a specific URL without asking me. It's rather presumptuous.

To combat this, I set up multiple profiles in Firefox and uncheck "open this profile by default" in the Profile Manager. Anytime this annoying behavior occurs I am presented with the profile manager, which I can dismiss if I never asked to go to a web site.

Can EdgeDeflector operate the same way--intercepting *all* URI/URL open attempts? If not can it be adapted to do so?

**Comment by da2x** [comment]
This isn’t something EdgeDeflector supports, nor does it sound like a very useful feature. This isn’t something I’ll work on or add to EdgeDeflector. However, please feel free to fork EdgeDeflector.

Please see the discussion in [issue #16](https://github.com/da2x/EdgeDeflector/issues/16). You could change the implementation discussed there to throw up a prompt dialog asking whether you want to open the URL or not. What you’d need to change in addition to what is discussed there is the URI registration on [line 84](https://github.com/da2x/EdgeDeflector/blob/459f2571c1/EdgeDeflector/Program.cs#L84) from `microsoft-edge` to `http` and `https` to work on regular links/allow your program to be set as the default web browser.

**Comment by earthbound19** [comment]
Thx for that info and pointing me to the other issue. I'm tempted :) and cloning the repo at least . . .
