### ISSUE TITLE
Cant change from edge

### ISSUE THREAD

**Issue by Nirgranth** [da2x/EdgeDeflector#171]
![image](https://user-images.githubusercontent.com/48947296/147808223-e845cae2-1b26-4452-af81-5f6dfde30620.png)
Tried via app too same thing Defector doesn't show up
![image](https://user-images.githubusercontent.com/48947296/147808327-e29fcf0a-718d-44f4-97c0-99b6e735c281.png)

**Comment by atomicf4ll** [comment]
#141

**Comment by LegendDestroyer6584** [comment]
You can use MSEdgeRedirect for now.
Click [here](https://github.com/rcmaehl/MSEdgeRedirect) for the Github
Click [here](https://github.com/rcmaehl/MSEdgeRedirect/releases/latest/download/MSEdgeRedirect.exe) for download

**Comment by LegendDestroyer6584** [comment]
You can use MSEdgeRedirect for now.
Click [here](https://github.com/rcmaehl/MSEdgeRedirect) for the Github
Click [here](https://github.com/rcmaehl/MSEdgeRedirect/releases/latest/download/MSEdgeRedirect.exe) for download

**Comment by da2x** [comment]
Duplicate of #141.
