### ISSUE TITLE
Doesn't this group policy do the same thing as your app? "Configure web-to-app linking with app URI handlers"

### ISSUE THREAD

**Issue by rugabunda** [da2x/EdgeDeflector#175]
"Administrative Templates\System\Group Policy\Configure web-to-app linking with app URI handlers"

> "This policy setting determines whether Windows supports web-to-app linking with app URI handlers.
> Enabling this policy setting enables web-to-app linking so that apps can be launched with a http(s) URI.
> Disabling this policy disables web-to-app linking and http(s) URIs will be opened in the default browser instead of launching the associated app.
> If you do not configure this policy setting, the default behavior depends on the Windows edition. Changes to this policy take effect on reboot."

**Comment by rugabunda** [comment]
And: **Admin templates\Windows Components\App Runtime\Block launching desktop apps associated with a URI scheme**

> This policy setting lets you control whether Windows Store apps can open URIs using the default desktop app for a URI scheme. Because desktop apps run at a higher integrity level than Windows Store apps, there is a risk that a URI scheme launched by a Windows Store app might compromise the system by launching a desktop app.
> 
> If you enable this policy setting, Windows Store apps cannot open URIs in the default desktop app for a URI scheme; they can open URIs only in other Windows Store apps.
> 
> If you disable or do not configure this policy setting, Windows Store apps can open URIs in the default desktop app for a URI scheme.
> 
> Note: Enabling this policy setting does not block Windows Store apps from opening the default desktop app for the http, https, and mailto URI schemes. The handlers for these URI schemes are hardened against URI-based vulnerabilities from untrusted sources, reducing the associated risk.

**Comment by da2x** [comment]
No, it's related but not the same.
