### ISSUE TITLE
EdgeDeflector Not listed

### ISSUE THREAD

**Issue by iCancerous** [da2x/EdgeDeflector#177]
EdgeDeflector not listed in default apps under MICROSOFT-EDGE
![Screenshot 2022-03-19 022339](https://user-images.githubusercontent.com/34277817/159110084-12400bcc-c22e-40a3-b65d-ab29a67d0f11.png)

**Comment by iCancerous** [comment]
Proof of installation
![Screenshot 2022-03-19 022507](https://user-images.githubusercontent.com/34277817/159110120-45d3e517-a094-463a-8826-62c1bc235fe0.png)

**Comment by BenPVandenberg** [comment]
Microsoft has blocked the deflector from working as intended in newer win10 versions and win11. [Reference](https://github.com/da2x/EdgeDeflector/issues/141#issuecomment-966402781)

**Comment by SquaredStudios-MC** [comment]
nooooooooooooooooooooooooooooooooo damn it i really need this
