### ISSUE TITLE
A Different Outcome Every Time

### ISSUE THREAD

**Issue by bombsoda** [da2x/EdgeDeflector#19]
As of yesterday, I have re-downloaded, installed, tried to run, restarted, re-ran, uninstalled, deleted, and restarted at least 15 times.  Sometimes I actually get the pop-up after installation, but the instruction to "Run the installer once to configure your system" does absolutely nothing.  Perhaps it runs and doesn't tell me what it is doing?  Fine, I will give it the benefit of the doubt.  It still doesn't work however. 

Sometimes the result is that Cortana will perform a web search in my chosen browser, but she pops up a Bing page to do so! So the result is that I have one tab open in Firefox, to this website, and another tab next to it is open to Bing and Bing's search results. Now Cortana isn't doing anything whatsoever. It won't pop up pages, tabs, otherwise acknowledge what you have said in any way.

I'd delete it altogether, but the resources at my disposal indicate that it won't just become an old-fashioned search bar that can access the internet as well as internal files, which is what I would love it to become. Hmm.  I strayed away from this page for a moment to turn on some music, now no other files will load!

Unfortunately, this computer is  Windows 10 that is completely updated with the creator's update and whatever other updates you get when you fire up a new pc. I guess I am going to uninstall EdgeDeflector again, just to see if I can magically use other programs again.  Have any tips for getting this thing to work?

**Comment by da2x** [comment]
Please verify that you’re using [EdgeDeflector version 1.1.1](https://github.com/da2x/EdgeDeflector/releases/tag/v1.1.1.0). The previous version stopped working in an update that arrived after the Creator’s Update. Windows changed how links worked, and that broke EdgeDeflector’s link-interception capabilities.

First of all, EdgeDeflector can’t interfere with what you’re seeing inside the Start menu/Cortana or the search results displayed therein. There is no codepath that connects the two whatsoever. I’m afraid what you’re experiencing is just Windows 10 being it’s usual self. Search [isn’t a great experience](https://ctrl.blog/entry/windows-start-search-results) in Windows 10 to begin with.

EdgeDeflector only kicks in when you actually click on a link in Cortana (and some other Windows apps). It doesn’t modify the app in any way, it intervenes after the link “has left” the app or Cortana and before it reaches Microsoft Edge. Hence the name, EdgeDeflector, as it deflects links away from Edge.

Secondly, Cortana always opens Bing web searches. She/it is Microsoft’s primary method of driving Windows users to use their search engine. You can use extensions in your web browser to redirect bing.com to google.com if you don’t like Bing search results. (You shouldn’t be using Cortana at all for web searches if you don’t like Bing. But that is another discussion.)

If links won’t open at all, please check your default app and protocol associates. You can do this from within the Windows Settings app: Apps: Default apps. Check that Web browser is set to your preferred browser. Next scroll to the bottom of the Default apps list, and click Choose default by protocol. Locate the name MICROSOFT-EDGE and verify that it’s set to EdgeDeflector. You can click the app name to change it if that isn’t the case.
