### ISSUE TITLE
Fix interception of links from lock screen

### ISSUE THREAD

**Issue by tech4him1** [da2x/EdgeDeflector#21]
If I try to click a link on the Windows 10 lock screen (using the Windows Spotlight pictures), it will normally open in Microsoft Edge, but if I change the `microsoft-edge` protocol to EdgeDeflector, the links simply do not work.

**Comment by da2x** [comment]
I can’t reproduce this problem. Links on the lock screen open a new tab in my default browser if it’s running, or starts it if I don’t have it open.

Are you running [the latest version](https://github.com/da2x/EdgeDeflector/releases/latest)?

Does your browser open if you press `Win key + R`, type in `microsoft-edge:https://example.com`, and press Enter?

**Comment by tech4him1** [comment]
I'm sorry, it seems to be working after a restart. In an earlier version of the program, though, it was broken only on the lock screen and not anywhere else, so I just assumed that was what it was again. Thanks!

**Comment by da2x** [comment]
Great! Just let me know if you run into any problems.
