### ISSUE TITLE
Cortana utilizing Google, and Google Chrome to open searches, But not Taskbar links

### ISSUE THREAD

**Issue by skysco** [da2x/EdgeDeflector#26]
Recently I have discovered the wonders of Edge Deflector and am beginning to understnand it a little more now that it is working properly for me. Although, with that being said, I have came to notice that the links that I have created a desktop, and then a taskbar icon for(I keep my school website, email down there for easy access) (Settings -> More Tools -> Add to Desktop, and then drag down onto task bar) continue to open within Microsoft Edge. I am just wondering if there is perhaps something that I may have missed that could potentially enable this feature as this was my sole purpose for investigating the concept initially. Thank you for any assistance in accomplishing this. 

![image](https://user-images.githubusercontent.com/32892631/31704646-413815d8-b3b0-11e7-8e0a-ad054f5b1024.png)
![image](https://user-images.githubusercontent.com/32892631/31704662-4a6a8c08-b3b0-11e7-80ab-d0561581df10.png)
![image](https://user-images.githubusercontent.com/32892631/31704667-53d9305a-b3b0-11e7-904c-496de47ded00.png)
![image](https://user-images.githubusercontent.com/32892631/31704688-620d3a4a-b3b0-11e7-982c-4cd65882ab68.png)

**Comment by da2x** [comment]
It’s not opening in Edge. You’re opening it in “chromeless” mode in Chrome; which is what Chrome uses for installed web apps (“add to desktop”).
