### ISSUE TITLE
Changing search engine

### ISSUE THREAD

**Issue by Javrd** [da2x/EdgeDeflector#27]
Could you add any option on the installer (or just a .cfg file) where you could change the search engine used for "web results"?

**Comment by Javrd** [comment]
Sorry I didn't see this post https://github.com/da2x/EdgeDeflector/wiki/Not-replacing-your-search-engine

**Comment by da2x** [comment]
That is okay. There are several great browser extensions that does this already. I see no need to reinvent the wheel.
