### ISSUE TITLE
1709

### ISSUE THREAD

**Issue by jiaaa621** [da2x/EdgeDeflector#28]
Hi, i am having problem on 1709 check log- 
![image](https://user-images.githubusercontent.com/32957796/31819775-6e12a740-b59e-11e7-9d31-934d20d5b0d9.png)
![image](https://user-images.githubusercontent.com/32957796/31819782-77ac1fca-b59e-11e7-9b8b-bf46b8c23ad0.png)
Any Ideas? 
Thanks

**Comment by da2x** [comment]
Please update to the [latest release](https://github.com/da2x/EdgeDeflector/releases/latest), version 1.1.0, and let me know if you’re still seeing the problem.

**Comment by jiaaa621** [comment]
ohhh sorry, my mistake, 1.1 worked thank you
