### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by TheWebAuthor** [da2x/EdgeDeflector#29]
I get "Google Chrome is unresponsive. Relaunch now?" dialog whenever I click on an article in Cortana.

**Comment by da2x** [comment]
Please provide more details. What version of EdgeDeflector are you running?

**Comment by TheWebAuthor** [comment]
I'm using the latest version. Any link I click on whether it's in an email or Cortana, I get the same window, and it doesn't launch the new tab in Chrome. Chrome is already open.

**Comment by da2x** [comment]
Press Windows key and R, and type http://example.com

Does the same thing happen?

**Comment by TheWebAuthor** [comment]
Yes

**Comment by da2x** [comment]
Then this is an issue with Chrome and not EdgeDeflector.
