### ISSUE TITLE
How do i uninstall

### ISSUE THREAD

**Issue by clmcgrath** [da2x/EdgeDeflector#3]
This isn't working after the latest windows 10 update,  how do i unregister the  EdgeDeflector functionality

**Comment by goodpunk6** [comment]
still works for me.  check your setup.

**Comment by clmcgrath** [comment]
it registers and shows up and a fresh winodws 10 1607 install but it doesn't do anything after you set default to EdgeDeflector

**Comment by clmcgrath** [comment]
i just want to try reinstalling it

**Comment by goodpunk6** [comment]
Think this may have happened to me.  i would select edgedeflector and the
box wouldn't change from just being a '+' sign.  I uninstalled it and
reinstalled.  That did the trick.

**Comment by da2x** [comment]
> i just want to try reinstalling it

Run edgedeflector.exe again manually once. No need to uninstall first.

> how do i unregister the EdgeDeflector functionality

https://github.com/da2x/EdgeDeflector/wiki/Uninstall

**Comment by clmcgrath** [comment]
Thanks reinstall worked 
:)

**Comment by clmcgrath** [comment]
I think it had to do more with something with my chrome installation as I tried re-running edgedeflector several times restarting as well reinstalling both seems to have worked
