### ISSUE TITLE
not working after fall creators update

### ISSUE THREAD

**Issue by misterjupiter** [da2x/EdgeDeflector#30]
edge-deflector stopped working after upgrading windows 10 with the fall creators update to v.1709.
Manually setting edge-deflector as standard in System-Settings > Apps > Standard-Apps > By protocol to use edge-deflector for MIRCOSOFT-EDGE doesn't work either.

**Comment by da2x** [comment]
Duplicate of issue #/14. Please upgrade to the [latest version](https://github.com/da2x/EdgeDeflector/releases).
