### ISSUE TITLE
Very slow response time

### ISSUE THREAD

**Issue by gabrielqv** [da2x/EdgeDeflector#34]
HI Pal, thanks for the great extension it is actually very useful as I like having a good search bar in windows, it was actually like the third I installed after a new windows install. however this time around I can't get it working properly, I have installed and the rogram works, however it is very slow, like I have to wait at least 1 minute to get a result.
the only circumstances that I know of my computer is that I used an offline account this time, (no Microsoft login) and I have changed some lang settings but apart from that I have done nothing at all! I don't know how to debug it, I created a dump file but it has a lot of nonsense in it, and I clicked in analyze wait chain to find only gebsvchost sihost nodes

**Comment by da2x** [comment]
Hi, please clarify when you notice the slowdown? EdgeDeflector is only involved after you click on a link. EdgeDeflector itself doesn’t really do much and shouldn’t cause any slowdowns. I suspect you’re either noticing slowdown in Windows shell itself or maybe your web browser.

To test:
  1. Quit your browser
  2. Press Win+R, type `https://example.com`, and press Enter
  3. Quit your browser
  4. Press Win+R, type `microsoft-edge:https://example.com`, and press Enter

Is step 2 a lot faster than step 4? Test a few times, and let me know what your perceived performance is like.

**Comment by picodaguy** [comment]
Hi, I am also getting this issue with version 1.1.3.0.  after searching I get a loading wheel that goes away, then after maybe a minute I get the chrome browser open. I did the steps above and step one has the issue, step two opens immediately. thanks in advance.

**Comment by da2x** [comment]
I highly doubt this has anything to do with EdgeDefelctor. You could try to reset your browser profile (delete the user data directory). You’ll loose all history and extensions, but should speed up startup time for any browser.
