### ISSUE TITLE
Website name not working

### ISSUE THREAD

**Issue by razorrider7** [da2x/EdgeDeflector#35]
When I input a website, not a search, Chrome doesn't open. For example, if I type `google is cool` and hit enter, Chrome opens and correctly searches "google is cool".
But if I type `bestbuy.com`
and hit enter, nothing happens. I am running the latest Windows 10 Home, and just downloaded the latest EdgeDeflector.

**Comment by razorrider7** [comment]
Just figured out why. It tries to open edge, rather than searching up the site in bing. See [here](https://i.imgur.com/w1L1oEc.png).

**Comment by da2x** [comment]
Oh, that is interesting. I can’t reproduce the problem, however.

Here is a special debug version you can run to collect the information I need to fix this. Unzip it, right-click on the .exe and run it as administrator once (nothing should happen). After doing this, you can reproduce the problem by searching for "google.com" in Cortana as normal. This should open a special URL on GitHub. Send me this URL and I should have what I need to fix this. Thank you for reporting the issue and thanks for the help.

EdgeDeflector_uri_debug.zip

**Comment by da2x** [comment]
This should be fixed in [version 1.1.3.0](https://github.com/da2x/EdgeDeflector/releases/tag/v1.1.3.0).

**Comment by razorrider7** [comment]
Yeah, it's fixed. Thanks!
