### ISSUE TITLE
Program Not Working

### ISSUE THREAD

**Issue by jtborrelli** [da2x/EdgeDeflector#36]
Hello!

I downloaded the program and it wasn't giving me the option to select EdgeDeflector when I used the Cortana search bar. So, I restarted my computer and installed the newest windows updates. I went to Cortana again and this time set EdgeDeflector as my default. I then went to search something and now nothing happens. It doesn't open up in edge or Chrome. Chrome is set as my default browser and I even tried reinstalling EdgeDeflector with no luck. Any idea what might be going wrong?

Thanks

**Comment by da2x** [comment]
Please test these thing for me:

1. Press Win+R, type https://example.com, and Press enter
1. Press Win+R, type microsoft-edge:https://example.com, and Press enter

Which of them opens your default browser?

If the above works as expected, could you please download this test build, unzip, right-click and run as admin 8nothing should happen). Then reproduce the problem you mentioned and send me the URL that opens?
[EdgeDeflector_uri_debug.zip](https://github.com/da2x/EdgeDeflector/files/1422933/EdgeDeflector_uri_debug.zip)

**Comment by jtborrelli** [comment]
Option one opens up in Chrome and option 2 prompts me to download an app
through the windows store. When I try your fix,
https://github.com/#microsoft-edge:?launchContext1=Microsoft.Windows.Cortana_cw5n1h2txyewy&url=https%3A%2F%2Fwww.bing.com%2Fsearch%3Fq%3Duiuc%26filters%3Dufn%253a%2522university%2Bof%2Billinois%2Bat%2Burbanachampaign%2522%2Bsid%253a%25225074dce8-d9fd-6211-28ec-a961ef904f4b%2522%26form%3DWNSGPH%26qs%3DMB%26cvid%3D5a1cb6ff4acf48a8aba01bcef90a146f%26pq%3Duiuc%26cc%3DUS%26setlang%3Den-US%26nclid%3D5ABEE86577981FDBF9EC649CBEAFE1C5%26ts%3D1509680887219%26nclidts%3D1509680887%26tsms%3D219?%3flaunchContext1%3dMicrosoft.Windows.Cortana_cw5n1h2txyewy%26url%3dhttps%253A%252F%252Fwww.bing.com%252Fsearch%253Fq%253Duiuc%2526filters%253Dufn%25253a%252522university%252Bof%252Billinois%252Bat%252Burbanachampaign%252522%252Bsid%25253a%2525225074dce8-d9fd-6211-28ec-a961ef904f4b%252522%2526form%253DWNSGPH%2526qs%253DMB%2526cvid%253D5a1cb6ff4acf48a8aba01bcef90a146f%2526pq%253Duiuc%2526cc%253DUS%2526setlang%253Den-US%2526nclid%253D5ABEE86577981FDBF9EC649CBEAFE1C5%2526ts%253D1509680887219%2526nclidts%253D1509680887%2526tsms%253D219
is the domain I get

**Comment by da2x** [comment]
Thanks for confirming the problem, this is fixed in 1.1.3.0.
