### ISSUE TITLE
Nothing happens when using Continue on PC

### ISSUE THREAD

**Issue by yashrastogi** [da2x/EdgeDeflector#38]
Your latest version works with cortana fine! :)
But nothing happens when using continue on PC not even edge opens...

**Comment by da2x** [comment]
Please test these thing for me:

1. Press Win+R, type https://example.com, and Press enter
1. Press Win+R, type microsoft-edge:https://example.com, and Press enter

Which of them opens your default browser?

If the above works as expected, could you please download this test build, unzip, right-click and run as admin 8nothing should happen). Then reproduce the problem you mentioned and send me the URL that opens?
[EdgeDeflector_uri_debug.zip](https://github.com/da2x/EdgeDeflector/files/1422933/EdgeDeflector_uri_debug.zip)

**Comment by yashrastogi** [comment]
Both open in my preferred browser (not Edge)
When using Continue on my PC, doesn't work: https://github.com/#microsoft-edge:?launchContext1=TimelineActivityId&launchContext2=2d6a52ae-b0f0-497e-9907-752754e4696d&url=https%3A%2F%2Fwww.google.co.in%2Fwebhp%3Fclient%3Dms-android-google%26source%3Dandroid-home%26gws_rd%3Dcr%2Cssl%26dcr%3D0%26ei%3DggD7WcvMMsyEvQT6tLH4Bg?%3flaunchContext1%3dTimelineActivityId%26launchContext2%3d2d6a52ae-b0f0-497e-9907-752754e4696d%26url%3dhttps%253A%252F%252Fwww.google.co.in%252Fwebhp%253Fclient%253Dms-android-google%2526source%253Dandroid-home%2526gws_rd%253Dcr%252Cssl%2526dcr%253D0%2526ei%253DggD7WcvMMsyEvQT6tLH4Bg

**Comment by da2x** [comment]
Thank you!

This should be fixed in [version 1.1.3.0](https://github.com/da2x/EdgeDeflector/releases/tag/v1.1.3.0).
