### ISSUE TITLE
don't search in google

### ISSUE THREAD

**Issue by clockvoid** [da2x/EdgeDeflector#4]
I want to search in google, but Cortana must search in Bing.
So, I suggest changeing a method that named RewriteMsEdgeUriSchema like

    static string RewriteMsEdgeUriSchema(string uri)
    {
        //changed area start
        string new_uri = "";
        char[] separator_chars = { '&', '?' };
        string[] words = uri.Split(separator_chars);
        Regex match_question = new Regex("^q=*");
        foreach (string s in words) {
            if (match_question.IsMatch(s)) {
                new_uri = "https://www.google.co.jp/search?" + s + "&gws_rd=ssl";
                break;
            }
        }
        //changed area end

        if (IsHttpUri(new_uri))
        {
            return new_uri;
        }

        return "http://" + new_uri;
    }

thanks.

**Comment by da2x** [comment]
Thank you for your interest in EdgeDeflector. Not going to happen. I’m not going to promote one search engine over the other. Feel free to fork EdgeDeflector and relaunch it as EdgeAndBingDeflector.

You’d be better served by doing this redirection in a browser extension. There are existing browser extensions that already redirects Bing Search to Google Search.

**Comment by clmcgrath** [comment]
Chrometana is probably the best extension for this currently and lets you choose from 3 search engines at the moment 
*note i i have nothing to do with the extension this is just a recommendation based on my own experiences
