### ISSUE TITLE
EdgeDeflector not Opening Chrome

### ISSUE THREAD

**Issue by BurgP7** [da2x/EdgeDeflector#40]
Hi. I tried installing EdgeDetector, but it doesn't work. Even after setting the proper protocol to EdgeDeflector, when a search is made using Cortana or the search bar, I get a loading pinwheel next to the cursor, and then nothing happens. It seems like EdgeDeflector runs, but doesn't actually do anything. I'm not sure how to fix this. Thanks!

**Comment by AndyParka** [comment]
Hi, After using edge deflector for months perfectly, I'm now having this same issue. I've tried reinstalling chrome and edgedeflector (and assigning the protocol) with same results described by BurgP7. Running Windows 10 Fall Creators update.

**Comment by da2x** [comment]
Which version of EdgeDeflector are you guys running? Be sure to upgrade to the [latest release](https://github.com/da2x/EdgeDeflector/releases/latest).

**Comment by AndyParka** [comment]
Can't believe I missed this, thank you. This new version worked for me. I hope this fixed it for BlrgP7 too.

**Comment by hennessyp** [comment]
I'm having the same problem. I've got the latest version (1.1.3.0) and running https://example.com and microsoft-edge:https://example.com both open the example page in Chrome. However like BurgP7, when I search in Cortana I get a loading pinwheel next to the cursor, and then nothing happens. How can I fix this?
