### ISSUE TITLE
Malwarebytes flagging Edge Deflector

### ISSUE THREAD

**Issue by Madeupname722** [da2x/EdgeDeflector#44]
Are you aware that Malwarebytes says this program is malware?
This makes me nervous as github repositories have been hacked in the past.

![capture](https://user-images.githubusercontent.com/24537286/33402618-ed759816-d511-11e7-93fa-9c426a33e914.JPG)

**Comment by da2x** [comment]
Please see issue #43, and report the false positive to your antivirus definition provider as a false positive. There is nothing I can do about it.
