### ISSUE TITLE
Uninstallation breaks Cortana

### ISSUE THREAD

**Issue by Madeupname722** [da2x/EdgeDeflector#45]
OK, so I uninstalled this vie the classic control panel now Cortana is broken.

When I click on any of the web results, nothing happens. I suspect the there's no default app set for the specially crafted urls any more.

Can you please explain how to get the normal function back?

**Comment by Madeupname722** [comment]
I found it. In settings default apps, scroll down to the bottom and click on "Choose default app by protocol" and then scroll down to "microsoft-edge" and change it back to edge.

**Comment by da2x** [comment]
The uninstaller removes its own registry keys; and leaves it up to Windows to manage the user’s preferences. This problem resolves itself if you log out and back in again or install any other software.
