### ISSUE TITLE
EdgeDeflector will not work

### ISSUE THREAD

**Issue by budgidiere** [da2x/EdgeDeflector#52]
Ok so I installed edge deflector and set everything up, but to my surprise, it does not work. It briefly opens a new chrome tab then It closes. Help would be appreciated! P.S. I tried search with my browser and it dose not work there either.

**Comment by da2x** [comment]
I’m going to need a lot more details from you. It sounds like you have a problem with Chrome and not EdgeDeflector. What exactly are you doing? and what exactly happens? Please describe the problem in more detail.

**Comment by budgidiere** [comment]
When I try to have Cortana open a link it opens a tab and instantly closes. I tried it with opera and it just opens a new tab. That's all that happens.

**Comment by da2x** [comment]
Press Windows-key+R, type microsoft-edge:https://example.com, and then press Enter. Does the same thing happen?

**Comment by budgidiere** [comment]
It opens example.com in chrome. The same thing still happens with Cortana.

**Comment by securus777** [comment]
Same here actually. I'm experiencing all of these same issues. Running Windows 1709. I see EdgeDeflector pop up in Task Manager, but then nothing in chrome. Your step above does work.

**Comment by da2x** [comment]
Please open Microsoft Edge: Settings: Advanced Settings. Is the option “Optimize taskbar web search results for screen readers” enabled? Does EdgeDeflector work if you disable it/enable it?

**Comment by securus777** [comment]
Mine was disabled. Upon enabling it, start web results open in Internet Explorer. EdgeDeflector did not show up in Task Manager when this happens. Disabling it again returned me to how it all was working before.

**Comment by budgidiere** [comment]
I tried this on my laptop and it still doesn't not work.

**Comment by budgidiere** [comment]
Ok so I tried going to "www.example.com" from Cortana and tried some other websites and it seems that, opening webs sites works but not searching.

**Comment by da2x** [comment]
@budgidiere, thanks for testing. Could you please download, unzip, and run this once as admin: [test build](https://github.com/da2x/EdgeDeflector/files/1422933/EdgeDeflector_uri_debug.zip). Then try a search in Cortana, and post the address of the resulting tab in here. (Delete the downloaded file and reinstall EdgeDeflector after testing.) This will help me identify and resolve the issue.

**Comment by budgidiere** [comment]
Here you go: https://github.com/#microsoft-edge:?launchContext1=Microsoft.Windows.Cortana_cw5n1h2txyewy&url=https%3A%2F%2Fwww.bing.com%2Fsearch%3Fq%3Dwhat%2Bis%2Bthe%2Bmeaing%2Bof%2Blife%26form%3DWNSGPH%26qs%3DSW%26cvid%3Dece901fc16f7471fb0e7d09d646fa88a%26pq%3Dwhat%2Bis%2Bthe%2Bmeaing%2Bof%2Blife%26cc%3DUS%26setlang%3Den-US%26nclid%3D1B5CEC335DEB0AF80D4424F32EA2D78D%26ts%3D1519424451256%26nclidts%3D1519424451%26tsms%3D256?%3flaunchContext1%3dMicrosoft.Windows.Cortana_cw5n1h2txyewy%26url%3dhttps%253A%252F%252Fwww.bing.com%252Fsearch%253Fq%253Dwhat%252Bis%252Bthe%252Bmeaing%252Bof%252Blife%2526form%253DWNSGPH%2526qs%253DSW%2526cvid%253Dece901fc16f7471fb0e7d09d646fa88a%2526pq%253Dwhat%252Bis%252Bthe%252Bmeaing%252Bof%252Blife%2526cc%253DUS%2526setlang%253Den-US%2526nclid%253D1B5CEC335DEB0AF80D4424F32EA2D78D%2526ts%253D1519424451256%2526nclidts%253D1519424451%2526tsms%253D256

**Comment by budgidiere** [comment]
In case it helps my search was: "what is the meaning of life"

**Comment by aarepajuste** [comment]
I appreciate what you are doing a lot @da2x let us know if you need any further help

**Comment by da2x** [comment]
As far as I can tell, this isn’t a bug in EdgeDeflector. Every time I’ve managed to reproduce it it has either been caused by a corrupted protocol association in Windows or the browser refusing to open external links (both Chrome and Firefox does this — and I don’t know why). I can’t reproduce it on demand, but when _whatever happens happen_ that triggers this I can reproduce this with plain HTTP links and even without EdgeDeflector installed.

**Comment by securus777** [comment]
Latest version seemed to correct the issues I was having. Thanks!

**Comment by Methodician** [comment]
I just installed EdgeDeflector for the first time and was thrilled when it worked, ONCE, then all subsequent cortana searches open Edge again and it is not asking about default apps any more. I even tried re-installing EdgeDeflector and it did not help.

**Comment by da2x** [comment]
@Methodician did you try the [troubleshooting steps](https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting)?

**Comment by luigypro** [comment]
Same problem, I`d installed 
1) EdgeDeflector
2) and Chormetana Pro
3) and i put my preference web browser to "google chrome" 
4) and i searched in cortana whatever word an i selected open in "EDGEDEFLECTOR" BUT HERE ARE THE PROBLEM! i forgot place the arrow in "always open this type of file with this app...." 

I think that is the problem, because only works for me ONE TIME, since that nothing happens! I mean Cortana still give me results to BING to EDGE, im so sad : ( please help me!!!

**Comment by da2x** [comment]
@luigypro did you try the [troubleshooting steps](https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting)?

**Comment by Syberiyxx** [comment]
Edge deflector stopped working for me today. Typing in microsoft-edge:https://example.com in run just opens edge. I reinstalled edge deflector again and it's still failing to work.

**Comment by da2x** [comment]
> Edge deflector stopped working for me today. Typing in microsoft-edge:https://example.com in run just opens edge. I reinstalled edge deflector again and it's still failing to work.

@Syberiyxx, did you try the [troubleshooting steps](https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting)?

**Comment by Syberiyxx** [comment]
yes, reset browsers to defaults and reboot the computer. Edge is still opening when I search.

**Comment by molitar** [comment]
Ok the troubleshooting steps did not work for me but was easy fix.  I just went into default apps than use the option > Set defaults by app > Scroll down to Edge > Manage > set the "MICROSOFT-EDGE" to EdgeDeflector.  Done now it opens my Cortana Searches in my default browser.
