### ISSUE TITLE
EdgeDeflector stops working after restarting explorer.exe

### ISSUE THREAD

**Issue by dome187** [da2x/EdgeDeflector#57]
After killing the the `explorer.exe` process in the details tab and launching it again (`File -> New task`) EdgeDeflector stops working.

**Comment by da2x** [comment]
This isn’t an issue with EdgeDefelctor, sorry. EdgeDeflector doesn’t know anything about explorer.exe or the Windows Shell. The issue here is most likely that you’ve broken Windows’ ability to launch programs or corrupted the protocol association registry.
