### ISSUE TITLE
You don't have any way to send you a beer.

### ISSUE THREAD

**Issue by Sakata-MC** [da2x/EdgeDeflector#60]
Get us a link to send you a beer. Or pizza.  or some other donation.  You've earned it.

**Comment by da2x** [comment]
Thanks! You can use [LibrePay](https://en.liberapay.com/da/donate) or [PayPal](https://www.paypal.me/Aleksandersen/30usd).

You can also support me and thousands of other open source developers on GitHub, YouTubers, content creators, and websites by installing [Flattr](https://flattr.com/@da2x). You pay one monthly subscription (from $3), install their browser extension, and they’ll divide out your contribution among your top developers, creators, etc. at the end of the month. It’s like Patreon without the need of having individual subscriptions for every creator you want to support (and without paying credit card and processing fees for every single one separately).

**Comment by da2x** [comment]
@czerwinskilukasz1 thank you for your interest and for notifying me about the dead link. I've fixed the link now!

**Comment by lubokkanev** [comment]
A Bitcoin cash address would be useful too

**Comment by da2x** [comment]
> A Bitcoin cash address would be useful too

    bitcoin:36W88UqKcvRhy14vLB1GpwH11hjpCC3q9M

**Comment by lubokkanev** [comment]
The BTC fees are way too high for me. I'd like to send you BCH.
