### ISSUE TITLE
MSIX Support

### ISSUE THREAD

**Issue by picknassaro** [da2x/EdgeDeflector#63]
I've been repackaging applications with the [MSIX Packaging Tool](https://www.microsoft.com/en-us/store/r/msix-packaging-tool-preview/9n5lw3jbcxkf?rtc=1&wa=wsignin1.0), and the applications I've tested are all working really really well. I'd love to see if EdgeDeflector would still work when repackaged as an MSIX application. It would also no longer need its own uninstall executable, since it would be containerized and removable via the right click > uninstall method that store apps use.

**Comment by da2x** [comment]
EdgeDeflector doesn't have a Start menu listing.
