### ISSUE TITLE
Amazing tool.  User-picked search engine too?

### ISSUE THREAD

**Issue by mikesocha3** [da2x/EdgeDeflector#64]
Hello,

I'm wondering if it would be easy to add the functionality for this tool to also 'deflect' the bing hard-coded search engine too?  Or maybe I should make a fork or contribute?  Thoughts?

Thanks!
Mike

**Comment by da2x** [comment]
EdgeDeflector [won't bereplacing your search engine](https://github.com/da2x/EdgeDeflector/wiki/Not-replacing-your-search-engine).

Also, please press Win-key+F and leave feedback to Microsoft clearly stating that you would want to choose the what search engine you use in the Start menu. Consider filing a complaint with the government bureau in charge of consumer protections and investigating anti-competitive behavior as well.
