### ISSUE TITLE
Is there any way to replace Bing for Google?

### ISSUE THREAD

**Issue by TheRobberPanda** [da2x/EdgeDeflector#65]
Im sure you get this a lot, and Im sorry to bother you, but my only reason to use edge deflector is to use google as a search engine. Thanks in advance.

**Comment by mkody** [comment]
This is mentioned in the README: https://github.com/da2x/EdgeDeflector/wiki/Not-replacing-your-search-engine

**Comment by da2x** [comment]
Press Win key+F to send feedback to Microsoft. Report one issue to Microsoft about wanting Cortana to respect your default browser setting. Report another issue asking for an option to choose your preferred search engine.

You can also vote with your wallet and stop using Cortana altogether.

**Comment by Utopiah** [comment]
I don't understand. The ReadMe says "Users search provider preference is best served in their web browser of choice. If you wish to redirect searches in Bing to DuckDuckGo or Google Search, you may do so using an extension for your web browser of choice." but even though my browser setting is set on DuckDuckGo cf 

![image](https://user-images.githubusercontent.com/1076655/57451108-95f81080-7260-11e9-9bda-5ad9900201b6.png)

when I do the search that is deflected from Edge it doesn't respect my settings and does using Bing, cf

![image](https://user-images.githubusercontent.com/1076655/57451119-9f817880-7260-11e9-9b55-ca59d6a469a6.png)

Did I miss something?

**Comment by da2x** [comment]
Cortana is powered by Bing. When you're using Cortana you're opening links pointing to Bing. You can install an extension in your web browser that will redirect from for example Bing to Yahoo. However, that redirect isn't part of what this program does and you'll need to dig up such an extension on your own from your browser's extension store or catalog. (There where tens available for Firefox and Chrome at last count.)

**Comment by Utopiah** [comment]
Even a "normal" search is powered by Cortana?

![image](https://user-images.githubusercontent.com/1076655/57475872-93fc7480-7295-11e9-812d-0d1343c40546.png)
