### ISSUE TITLE
Add the ability to bypass EdgeDeflector

### ISSUE THREAD

**Issue by AnyRandomPerson** [da2x/EdgeDeflector#67]
Per example I'd like to run the following command :
`microsoft-edge://website.com`
However Deflector detects the request and opens the adress in my default browser.
What would be nice would be to have an additional argument EdgeDeflector will take account of and allow the adress to be opened in Edge like this :
`microsoft-edge://website.com -bypassdeflector`

**Comment by da2x** [comment]
There is no way to pass an argument. EdgeDeflector only receive an URI which it rewrites to make it respect the default web browser setting. There isn't any room for extending this.
