### ISSUE TITLE
Disable

### ISSUE THREAD

**Issue by mrandreastoth** [da2x/EdgeDeflector#68]
Would be nice to be able to temporarily disable EdgeDeflector without having to uninstall then reinstall (or hack the registry).

**Comment by da2x** [comment]
Why and when do you need to disable it? You can change your default browser in Windoes Settings: Apps and EdgeFeflector will open links in your indicated browser.

**Comment by mrandreastoth** [comment]
Because, sometimes, I need to follow links that, unfortunately, require Edge. And, no, disabling the default is not the right solution. The default browser is correct and should not have to change. It is the link management that needs to be temporarily overridden to restore default behaviour.

**Comment by klr1956** [comment]
I may be totally off base but can your issue be addressed by "Settings>Apps>Default apps" and then "Choose default apps by file type"? (I can't think of another scenario where you're forced to use Edge. But, even then ...)

**Comment by klr1956** [comment]
Can your issue be addressed by "Settings>Apps>Default apps>Choose default apps by file type"?

**Comment by olliebean** [comment]
The easiest way to do this is with the read protocol. If you add `read:` to the start of the URL in the properties of a bookmark or shortcut, it will open in Edge, regardless of EdgeDeflector being installed. The drawback is it opens in the reading view, but it just takes one click to switch to web view.
