### ISSUE TITLE
request: send cortana output to any window

### ISSUE THREAD

**Issue by Guru011** [da2x/EdgeDeflector#69]
i can't understand Microsoft gave Cortana only the ability to open a browser for searching. Could you make Edge Deflector send the Cortana search to any desired app/window? That would be great! Bye!

**Comment by iworthin** [comment]
Please stop emailing me about this. Thanks 😊

**Comment by Guru011** [comment]
i didn't mail you...i just made this topic

**Comment by da2x** [comment]
I can't make any changes to Cortana, no.
