### ISSUE TITLE
Chrome uses Bing as default browser regardless of Chrome settings

### ISSUE THREAD

**Issue by scottsemple** [da2x/EdgeDeflector#7]
I just set up EdgeDeflector. (Thanks for building it!)

Unfortunately, when I enter a search term in the W10 Start menu field, when my default browser opens (Chrome), Bing is used as the search engine. This happens regardless of the default search engine settings within Chrome.

I've gone so far as removing all other search engine options from the settings list, save for Google. Bing still opens with any search term that I enter using the Start menu search field.

Is this an EdgeDeflector issue? Or something else within Windows/Chrome?

**Comment by da2x** [comment]
EdgeDeflector just opens links in your preferred browser. When you search with Cortana, it defaults to using Bing search and Cortana asks your browser to open a link to Bing. Cortana could have told your browsers to open `? search-query` when you search for `search-query`. This would have used the default browser; unfortunately Cortana is a tool to promote Bing so it forces the use of Bing regardless of the default search engine settings in your browser (or in Edge).

EdgeDeflector is not an anti-Bing tool, just an anti-force-users-to-use-a-browser-other-than-their-default-browser tool. There are extensions available for Chrome available in the Google Web Store that will redirect Bing searches to Google.

Please open the Feedback app in Windows and tell Microsoft you’d like the freedom to use whatever browser and whatever search engine you like.
