### ISSUE TITLE
Automatic redirect to search engine?

### ISSUE THREAD

**Issue by ghost** [da2x/EdgeDeflector#70]
When typing in a "random word" in the search bar this leads to http://random word/ rather than e.g. an automatic redirect to a Google search for "random word". How do I fix this?

**Comment by aderchox** [comment]
> When typing in a "random word" in the search bar this leads to http://random word/ rather than e.g. an automatic redirect to a Google search for "random word". How do I fix this?

I don't have this problem, mine searches the "random word" properly. However, mine has another issue, it searches things in Chrome but through Bing. But I think I can find some hacks to resolve the search engine problem as well.
