### ISSUE TITLE
Cortana searches opening in Chrome but using bing.com

### ISSUE THREAD

**Issue by mikedeissder** [da2x/EdgeDeflector#73]
After installingED my Cortana searches are opening in Chrome but using bing.com not google.com for the search.  I've uninstalled and reinstalled several times.  The first install prompted me to select EdgeDeflector subsequent installs did not.   I had to select EdgeDeflector as the url-MicrosoftEdge protocol selection. Now when I search from the Cortana search bar the search is passed to chrome as a bing.com search and is never redirected to Google...

**Comment by da2x** [comment]
EdgeDeflector only enforces your operating-system-level default web browser setting. It doesn't change the links you're trying to open. When you use Cortana or Windows Search it will link you to Bing.

Press the Windows key + F to leave feedback for Microsoft that you'd like the option to use another search engine.

There are several extensions available for popular web browsers that will redirect Bing searches to Google. This functionality is outside the domain of EdgeDeflector, however.
