### ISSUE TITLE
How to build a project as an installer?

### ISSUE THREAD

**Issue by 1nfdev** [da2x/EdgeDeflector#75]
Dear **Daniel**, I'm not a Windows/C# programmer and I don't use Visual Studio _and that's why I couldn't build the project correctly_.

Could you add an instruction on building a project as an installed file? Or tell me how to do it.

**_I want to change the image of the application_** (`Icon.ico`) to a more appropriate one for me.

I use Visual Studio 2019 on Windows 10.

**Comment by da2x** [comment]
You only really ever see the icon once, but okay. Please free to contribute a better icon! You can provide PNGs of the icon in 256x256, 128x128, 64x64, 48x48, 32x32, 24x24, and 16x16px. You must affirm that you you’re okay contributing and distributing your new icon under the [project license (MIT)](https://github.com/da2x/EdgeDeflector/blob/master/LICENSE).


Build instructions:

1. Install VisualStudio
2. Open `EdgeDeflector.sln`
3. Choose `Build` from the top menu

Youl’ll find the compiled executable in the project folder. Running the program once as an administrator installs it in the current location. It’s ready for use after that. Move the executable into a folder where you’ll like to store it before running it.

To make the installer, you’ll need the [NullSoft Installer](https://nsis.sourceforge.io/). It’s a GUI program that needs two parameters: the [NSIS file](https://github.com/da2x/EdgeDeflector/blob/master/EdgeDeflector/resources/nsis_installer.nsi) and the executable you built earlier.
