### ISSUE TITLE
EdgeDeflector not working; Being sent to Edge

### ISSUE THREAD

**Issue by sluck1** [da2x/EdgeDeflector#76]
I am being sent to Microsoft Edge, still.

My PC's default browser which I set in Default Apps is Google Chrome. 

One time when I clicked a link on cortana search I was given a dialog box asking which app to use. I chose "EdgeDeflector" and I am almost positive I checked the "Use this app every time." box (if that box existed) because nothing I do (uninstall, click links, reinstall, click links) will ever make another dialog box appear again.

On that launch, when I explicitly clicked "Use EdgeDeflector" , the link was still opened in Microsoft Edge.

What is going on?

To preliminarily answer some of the first Q's you may have: 

In the "Run" dialog box,
microsoft-edge:www.google.com opens google.com with microsoft-edge
www.google.com opens google.com with Google Chrome

My OS is Windows 10 Home x64 Version 1903 OS build 18362.476 , and I hate Microsoft Edge, so let's fix this problem :)

**Comment by themonstrousdev** [comment]
I was having this issue too. 

I fixed it by doing the following steps:
1) Set your default Web Browser to your preferred browser
2) Click "Set defaults by app"
3) Search for Edge Deflector on the list and click it, then click "Manage"
4) There should only be one changeable option there name MICROSOFT-EDGE, change that to Edge Deflector
5) To check, open the "Run" dialogue box and type microsoft-edge:https://www.google.com

**Comment by da2x** [comment]
Have you followed [the troubleshooting steps](https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting)?

**Comment by sluck1** [comment]
Troubleshooting steps worked. Thank you and great software.

**Comment by erickzr** [comment]
Yes thank you for the great software, btw virustotal shows some issues with thet current file

**Comment by da2x** [comment]
> Yes thank you for the great software, btw virustotal shows some issues with thet current file

The detected “threats” are two URLs. You can evaluate them here. https://www.virustotal.com/gui/file/7ea4b60b3ab640472f616ec56cd519bd1006ccd59f6be81b5d9e5e2c157f584b/community Any URL is a potential threat.
