### ISSUE TITLE
Additional settings do not get saved

### ISSUE THREAD

**Issue by fronders** [da2x/EdgeDeflector#78]
Hello!
I am using Windows 10 x64 Build 1903 with Google Chrome Version 79.0.3945.130 (Official Build) (64-bit). EdgeDeflector version 1.1.3.0

Additional settings do not get saved by the extension.
For example I enable "open website" and select Apply to all Bing searches. 
It shows the message "preferences saved"
![image](https://user-images.githubusercontent.com/15352046/72603642-190a5400-3922-11ea-8757-32e658fbb3dd.png)
But after a reload they are again empty and take no effect on the app.

Also the radiobutton on "Apply to searches" doesn't work correctly, I can select both options:
![image](https://user-images.githubusercontent.com/15352046/72603727-3e975d80-3922-11ea-9612-b599aa722af6.png)

Would appreciate any assistance, thx.

**Comment by aderchox** [comment]
Hi @fronders, in case you're using "Chromtana" please use "Chromtana Pro" instead. It's free and is working fine for me.

**Comment by da2x** [comment]
This is the wrong repo.
