### ISSUE TITLE
Works on second attempt

### ISSUE THREAD

**Issue by jjmias** [da2x/EdgeDeflector#8]
Hi,

First off great program.  Mainly I see this with iCloud Notes from within Windows, it doesn't deflect to my default browser (Chrome) until the second try.

Open Notes > Notes open in Edge > Close Edge > open Notes again > Notes open in Chrome

Keep up the good work!

**Comment by da2x** [comment]
Could you please provide a sample of the URL? (Before it opens in your browser if at all possible.)

**Comment by jjmias** [comment]
So when you install iCloud for Windows it gives shortcuts to Apple Apps.  The location of this is @ C:\ProgramData\Microsoft\Windows\Start Menu\Programs\iCloud.  

This goes to the URL https://www.icloud.com/#notes or https://www.icloud.com/#notes2.

I hope that helps.

**Comment by da2x** [comment]
I totally dropped the ball on this one, sorry. I’ve investigated it, and can report that this has nothing to do with EdgeDeflector. iCloud doesn’t use `microsoft-edge:` URIs nor are they involved anywhere in the process. This is Windows misbehaving all on its own. (Sounds like yet another case of default apps database corruption.)
