### ISSUE TITLE
Orphaned files and registry keys after uninstalling

### ISSUE THREAD

**Issue by twity1337** [da2x/EdgeDeflector#80]
After uninstalling the program, there are still some files and the registry keys for registering the protocol handler left over.

Those are:
- The program directory itself (which is empty, because all files have been deleted)
- Registry key in "Classes"
- Registry key in "Capabilities"

The uninstaller should clean the system without leaving any garbage leftover. Furthermore it is necessary to remove the registry keys, because otherwise the default application does not get reset correctly.

**Comment by da2x** [comment]
> The program directory itself (which is empty, because all files have been deleted)

Users can chose to install to C:/. The NSIS installer system doesn’t have a way of determening whether people used the default directory and will leave an empty directory behind. It’s safer to leave an empty directory behind that won’t hurt a fly than to try to determine whether it’s safe to delete it.

> Registry key in "Classes"
> Registry key in "Capabilities"

These are protected by the system. Third-party apps can’t delete or change these. This is part of Windows’ default-browser protection mechanism. These will reset to the default the first time you open a URI and Windows discover that the programs are gone.
