### ISSUE TITLE
no longer working as of this week.

### ISSUE THREAD

**Issue by Mete0** [da2x/EdgeDeflector#83]
Ive tried all troubleshooting steps and can no longer get the searchbar to launch chrome

**Comment by da2x** [comment]
Hi, thank you for reporting. Please follow the steps and provide the same information that I requested here. It should hopefully be all the info I need to identify and fix the issue.
https://github.com/da2x/EdgeDeflector/issues/81#issuecomment-610463167

**Comment by dust213dust** [comment]
just linked and installed phone companion and deflector and its just not opening browser after continue on pc share

**Comment by da2x** [comment]
@dust213dust could you please follow the steps and provide the information [requested here](https://github.com/da2x/EdgeDeflector/issues/81#issuecomment-610463167)?

**Comment by da2x** [comment]
Duplicate of #81.
