### ISSUE TITLE
No longer working for me either

### ISSUE THREAD

**Issue by francescoboc** [da2x/EdgeDeflector#85]
Hi, first of all I'd like to thank you immensely for releasing this awesome little software for free on github! It's such a shame that we have to go through these "hacks" because Microsoft doesn't give us the freedom to choose our default internet browser.

I have used your software for some time, and it has worked perfectly. However it's been some days, maybe weeks, that it is not longer working. I followed all the steps in the troubleshooting page. Last time I did an uninstall/reinstall and a reboot and the problem was fixed for a while. Now the problem came back, and I don't want to reboot my machine because I have too much stuff open that I don't want to close...

Do you know if it is a known issue? Maybe coming from some recent Windows updates? And if it is fixable?

Thank you very much for your time.

**Comment by da2x** [comment]
https://github.com/da2x/EdgeDeflector/issues/81#issuecomment-610463167

**Comment by da2x** [comment]
Duplicate.
