### ISSUE TITLE
[Question] How I can change Cortana search engine?

### ISSUE THREAD

**Issue by xmha97** [da2x/EdgeDeflector#86]
Hello, I want to change the Cortana search engine.
How I can?

**Comment by da2x** [comment]
https://github.com/da2x/EdgeDeflector/wiki/Not-replacing-your-search-engine

**Comment by xmha97** [comment]
Okay, I saw that:
https://github.com/pulsejet/EdgeAndBingDeflector
Why not add this feature to your app?
