### ISSUE TITLE
Is it possible for you to create another version expect it searches the same query but using google search engine?

### ISSUE THREAD

**Issue by Mystik01** [da2x/EdgeDeflector#90]
Is it possible to create another version for people who want it so it changes to using google search engine? I understand you've said use an extension but I'm currently using opera and the only redirect i can find is chrometana but that's only available for chrome, can you now just add a configuration thing for different search engines in the setup wizard?
This text kind of feels rude against you,if it does feel rude im not trying to,  I'm just trying to explain what I mean an suggest something.

**Comment by Mystik01** [comment]
actually you've said no so dont bother replying

**Comment by da2x** [comment]
You can install and use Chrome extensions in Opera using this extension from Opera Software:
https://addons.opera.com/en/extensions/details/install-chrome-extensions/

Note that I can’t actually change what happens in the start menu. You’ll get Bing search results there no matter what. You’re using a Microsoft product, after all. The redirect extensions just replaces bing.com with google.com when you chose to continue the search in a browser.
