### ISSUE TITLE
When opening links send from phone to PC via phone companion app, always asks for browser first

### ISSUE THREAD

**Issue by RlyNeedBackup** [da2x/EdgeDeflector#95]
Hey, everytime I open a link send from my phone, I get a notification asking to choose how to open this file, I choose Chrome with the "use this always" checked, and it still appears every time I open a link

**Comment by da2x** [comment]
Do you see EdgeDeflector in the dialog? If not, then this issue isn't relevant.

**Comment by RlyNeedBackup** [comment]
> Do you see EdgeDeflector in the dialog? If not, then this issue isn't related to it.
That's how it looks
[https://i.imgur.com/gEbtw84.png](url)
With EdgeDeflector uninstalled I don't get this and links dont open at all, even with Edge.

**Comment by RlyNeedBackup** [comment]
Your Phone Companion app update fixed it
