### ISSUE TITLE
Suggestion: EdgeDeflector open's a specific profile of the default browser

### ISSUE THREAD

**Issue by harshit-hooda** [da2x/EdgeDeflector#99]
Hello, i have a suggestion to provide an option to open a specific browser profile. for example in google chrome, if there are two different chrome profiles (1 account signed in each profile), then EdgeDeflector provides an option to choose which profile to open (and also a choice to set a default profile). Also, if there is any way to also provide an option to open a specific account in that single browser profile then that would also be great. (and also a choice to set as a default account for specific profile)

This feature could be very helpful because as of now, the EdgeDeflector opens that profile of browser that was most recently used. There is not an option to open a specific profile every time irrespective of whether it was used recently or not. 

Thanks for reading and your time

**Comment by da2x** [comment]
No. Profile handling is browser-specific. I can't implement something generic for every browser. EdgeDeflector doesn't even have any idea what your default browser is.

Firefox has an option to ask you to pick a browser profile on start-up. This might meet your needs, but I'm not sure how it handles singletoning. Alternatively, Firefox's [container feature](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) can help you work with multiple isolated logins/sessions on the same sites within the one browser profile.

**Comment by harshit-hooda** [comment]
Okay, thanks for the information and references.
